"""add car_hist_table

Revision ID: 7bc6c3ba49c9
Revises: fea34d052bd6
Create Date: 2026-06-02 21:36:10.796684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc6c3ba49c9'
down_revision: Union[str, Sequence[str], None] = 'fea34d052bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_hist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_name', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('engine_type', sa.Text(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Text(), nullable=True),
    sa.Column('drive', sa.Text(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('steering_wheel', sa.Text(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('restyling', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('trim', sa.Text(), nullable=True),
    sa.Column('marka', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('year_month', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars_hist')
    # ### end Alembic commands ###
