"""add missing cols

Revision ID: fea34d052bd6
Revises: 6c1a25fb1170
Create Date: 2026-05-29 10:01:34.481058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea34d052bd6'
down_revision: Union[str, Sequence[str], None] = '6c1a25fb1170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('engineDisplacement', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'location')
    op.drop_column('cars', 'engineDisplacement')
    # ### end Alembic commands ###
