models = {
    "Audi": {
        "100": [2, 3, 4],
        "200": [2, 3],
        "80": [2, 3, 4],
        "90": [2, 3, 4],
        "A1": [1, 2],
        "A2": [1],
        "A3": [1, 2, 3, 4],
        "A4": [1, 2, 3, 4, 5],
        "A4 allroad quattro": [1, 2],
        "A5": [1, 2],
        "A6": [1, 2, 3, 4, 5],
        "A6 allroad quattro": [1, 2, 3],
        "A7": [1],
        "A8": [1, 2, 3],
        "Cabriolet": [1],
        "Coupe": [1, 2],
        "Q2": [1],
        "Q3": [1],
        "Q5": [1, 2],
        "Q7": [1, 2],
        "Q8": [1],
        "RS Q3": [1],
        "RS4": [1, 3],
        "RS5": [1],
        "RS6": [2],
        "S2": [1],
        "S3": [1, 2],
        "S4": [1, 2, 3, 4, 5],
        "S5": [1, 2],
        "S6": [1, 2, 3, 4],
        "S8": [1, 2, 3],
        "TT": [1, 2],
        "TT RS": [2],
        "TTS": [2],
        "V8": [1],
        "e-tron": [1],
    },
    "BMW": {
        "1-Series": [1, 2, 3],
        "2-Series": [1],
        "2-Series Active Tourer": [1],
        "2-Series Gran Tourer": [1],
        "3-Series": [1, 2, 3, 4, 5, 6, 7],
        "3-Series Gran Turismo": [6],
        "321": [1],
        "326": [1],
        "340": [1],
        "4-Series": [1],
        "5-Series": [1, 2, 3, 4, 5, 6, 7],
        "5-Series Gran Turismo": [6],
        "6-Series": [1, 2, 3],
        "7-Series": [1, 2, 3, 4, 5],
        "8-Series": [1, 2],
        "E3": [1],
        "M3": [2, 3, 4],
        "M5": [2, 3, 4],
        "M6": [2, 3],
        "X1": [1, 2],
        "X2": [1],
        "X3": [1, 2, 3],
        "X4": [1, 2],
        "X5": [1, 2, 3, 4],
        "X6": [1, 2, 3],
        "Z3": [1],
        "Z4": [1, 2],
        "i3": [1],
    },
    "BYD": {
        "F0": [1],
        "F3": [1],
        "F6": [1],
        "Flyer": [1],
        "G3": [1],
        "G6": [1],
        "S6": [1],
        "Song Max": [1],
    },
    "Bentley": {
        "Arnage": [1],
        "Continental": [1],
        "Continental GT": [1, 3],
        "Eight": [1],
        "Flying Spur": [1],
    },
    "Cadillac": {
        "ATS": [1],
        "BLS": [1],
        "Brougham": [1],
        "CTS": [1, 2, 3],
        "Catera": [1],
        "DTS": [1],
        "DeVille": [5, 7, 8, 9, 10],
        "Eldorado": [9, 10, 11, 12],
        "Escalade": [1, 2, 3, 4],
        "Fleetwood": [1, 2],
        "SRX": [1, 2],
        "STS": [1],
        "Seville": [2, 3, 4, 5],
    },
    "Chery": {
        "A11": [1],
        "A5": [1],
        "Amulet A15": [1],
        "Arrizo 5 Pro": [1],
        "Arrizo 7": [1],
        "Bonus 3 - A19": [1],
        "Bonus A13": [1],
        "Chery": [1],
        "CrossEastar": [1],
        "E5": [1],
        "Eastar": [1],
        "Fora A21": [1],
        "Karry": [1],
        "Kimo A1": [1],
        "M11": [1],
        "Oriental Son": [1],
        "QQ Sweet": [1],
        "QQ6 S21": [1],
        "Tiggo 2": [1],
        "Tiggo 3": [1],
        "Tiggo 3x": [1],
        "Tiggo 4": [1],
        "Tiggo 4 Pro": [1],
        "Tiggo 5": [1],
        "Tiggo 7": [1, 2],
        "Tiggo 7 Plus": [1],
        "Tiggo 7 Pro": [1],
        "Tiggo 7 Pro Max": [1],
        "Tiggo 8": [1],
        "Tiggo 8 Pro": [1],
        "Tiggo 8 Pro Max": [1],
        "Tiggo 8 Pro Plug-In-Hybrid": [1],
        "Tiggo T11": [1],
        "V5": [1],
        "Very A13": [1],
        "indiS S18D": [1],
    },
    "Chevrolet": {
        "Alero": [1],
        "Astro": [1, 2],
        "Avalanche": [1, 2],
        "Aveo": [1, 2],
        "Bel Air": [1],
        "Beretta": [1],
        "Blazer": [1, 2, 3],
        "Blazer S-10": [1, 2],
        "Camaro": [3, 4, 5, 6],
        "Caprice": [3, 4],
        "Captiva": [1, 2],
        "Cavalier": [2, 3],
        "Celebrity": [1],
        "Cobalt": [1, 2],
        "Colorado": [1],
        "Corsica": [1],
        "Corvette": [2, 3, 4, 5],
        "Cruze": [1, 2],
        "Damas": [1],
        "Epica": [1, 2],
        "Equinox": [1, 2, 3],
        "Evanda": [1],
        "Express": [1],
        "HHR": [1],
        "Impala": [4, 5, 6, 7, 9],
        "Lacetti": [1],
        "Lanos": [1],
        "Lumina": [1, 2],
        "Lumina APV": [1],
        "MW": [1],
        "Malibu": [7, 8, 9],
        "Metro": [2],
        "Monte Carlo": [3, 5],
        "Monza": [4],
        "Nexia": [1],
        "Niva": [1],
        "Nubira": [1],
        "Optra": [1],
        "Orlando": [1, 2],
        "Prisma": [1, 3],
        "Rezzo": [1],
        "S10": [1, 2],
        "Silverado": [1, 2, 8],
        "Sonic": [1],
        "Spark": [1, 2, 3, 4],
        "Spin": [1],
        "Starcraft": [1, 3, 4, 8],
        "Suburban": [8, 9, 10],
        "Tacuma": [1],
        "Tahoe": [1, 2, 3, 5],
        "Tracker": [1, 2, 3],
        "TrailBlazer": [1, 2],
        "Trans Sport": [1],
        "Traverse": [1],
        "Trax": [1],
        "Uplander": [1],
        "Van": [3],
        "Venture": [1],
        "Viva": [1],
        "Volt": [1, 2],
        "Yukon": [1],
    },
    "Citroen": {
        "2CV": [1],
        "AX": [2],
        "BX": [1],
        "Berlingo": [1, 2, 3],
        "C-Crosser": [1],
        "C-Elysee": [1],
        "C1": [1, 2],
        "C2": [1],
        "C3": [1, 2, 3],
        "C3 Aircross": [1],
        "C3 Picasso": [1],
        "C4": [1, 2],
        "C4 Aircross": [1],
        "C4 Cactus": [1],
        "C4 Picasso": [1, 2],
        "C4 Spacetourer": [1],
        "C5": [1, 2],
        "C6": [1],
        "C8": [1],
        "Citroen": [1, 2],
        "DS": [1],
        "DS3": [1],
        "DS4": [1],
        "DS5": [1],
        "Evasion": [1],
        "GS": [1],
        "Grand C4 Picasso": [1, 2],
        "Grand C4 Spacetourer": [1],
        "Jumpy": [1, 2, 3],
        "Nemo": [1],
        "Saxo": [1],
        "XM": [1, 2],
        "Xantia": [1],
        "Xsara": [1, 2],
        "Xsara Picasso": [1],
        "ZX": [1],
    },
    "Ford": {
        "Aerostar": [1],
        "B-MAX": [1],
        "Bronco": [1, 3, 4, 5, 6],
        "Bronco II": [1],
        "C-MAX": [1, 2],
        "Capri": [1, 2, 3],
        "Contour": [1],
        "Cougar": [1],
        "Crown Victoria": [1, 2],
        "EcoSport": [1, 2],
        "Econoline": [4],
        "Econovan": [2],
        "Edge": [1],
        "Escape": [1, 2, 3],
        "Escort": [2, 3, 4, 5, 6],
        "Everest": [1],
        "Excursion": [1],
        "Expedition": [1, 2, 3],
        "Explorer": [1, 2, 3, 4, 5],
        "F150": [3, 4, 5, 6, 7],
        "F250": [1, 2],
        "F350": [1, 2],
        "F450": [1, 4],
        "Fairlane": [1, 2, 5],
        "Festiva": [1, 2, 3],
        "Fiesta": [2, 3, 4, 5, 6, 7],
        "Five Hundred": [1, 3],
        "Flex": [1],
        "Focus": [1, 2, 3, 4],
        "Focus RS": [2],
        "Focus ST": [2, 3],
        "Ford": [1, 2, 3, 4, 5, 6],
        "Freda": [1],
        "Freestyle": [1],
        "Fusion": [1, 2],
        "Galaxy": [1, 2, 3],
        "Granada": [1, 2, 3],
        "Grand C-MAX": [1],
        "Ikon": [1],
        "Ixion": [1],
        "Ka": [1, 2],
        "Kuga": [1, 2],
        "Laser": [3, 4, 5],
        "Maverick": [2, 3],
        "Mondeo": [1, 2, 3, 4, 5],
        "Mustang": [1, 3, 4, 5, 6],
        "Orion": [1, 2, 3],
        "P100": [1, 3, 4, 5, 6],
        "Probe": [1, 2],
        "Puma": [1],
        "Ranger": [1, 2, 3],
        "S-MAX": [1],
        "Scorpio": [1, 2],
        "Sierra": [1],
        "Spectron": [1],
        "StreetKa": [1],
        "Taunus": [1, 2, 3, 6],
        "Taurus": [1, 2, 3, 4, 6],
        "Telstar": [2, 3, 4, 5],
        "Tempo": [2],
        "Territory": [1],
        "Th!nk": [1],
        "Thunderbird": [7, 9, 10, 11],
        "Tourneo": [1, 2, 3],
        "Tourneo Connect": [1, 2],
        "Tourneo Courier": [1],
        "Tourneo Custom": [1],
        "Windstar": [1, 2],
    },
    "Geely": {
        "Atlas": [1],
        "Binrui": [1],
        "Binyue": [1],
        "CK Otaka": [1],
        "Coolray": [1],
        "Emgrand": [1, 4],
        "Emgrand EC7": [1],
        "Emgrand EC8": [1],
        "Emgrand GL": [1],
        "Emgrand GT": [1],
        "Emgrand X7": [1],
        "FC": [1],
        "GC6": [1],
        "GS": [2],
        "Geely": [1],
        "LC Cross": [1],
        "MK": [1],
        "MK Cross": [1],
        "Monjaro": [1],
        "Otaka CK": [1],
        "Preface": [1],
        "SC7": [1],
        "SL": [1],
        "Tugella": [1],
        "Vision FC": [1],
        "Vision X3": [1],
    },
    "Genesis": {"G70": [1], "G80": [1]},
    "Haval": {
        "F7": [1],
        "F7x": [1],
        "H2": [1],
        "H5": [2],
        "H6": [1, 2],
        "H6 Coupe": [1],
        "H8": [1],
        "H9": [1],
        "Jolion": [1],
        "M6": [1, 2],
    },
    "Honda": {
        "Accord": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "Accord Inspire": [1],
        "Acty": [1, 2, 3, 4],
        "Airwave": [1],
        "Ascot": [1, 2],
        "Ascot Innova": [1],
        "Avancier": [1],
        "Beat": [1],
        "CR-V": [1, 2, 3, 4, 5],
        "CR-X": [1, 2],
        "CR-X del Sol": [1],
        "CR-Z": [1],
        "Capa": [1],
        "City": [1, 2, 3, 4, 5],
        "Civic": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "Civic Ferio": [1, 2, 3],
        "Civic Shuttle": [1, 2],
        "Civic Type R": [1, 2, 3],
        "Clarity": [2],
        "Concerto": [1],
        "Crider": [2],
        "Crossroad": [1, 2],
        "Crosstour": [1],
        "Domani": [1, 2],
        "Edix": [1],
        "Element": [1],
        "Elysion": [1],
        "Envix": [1],
        "FR-V": [1],
        "Fit": [1, 2, 3, 4],
        "Fit Aria": [1],
        "Fit Shuttle": [1],
        "Freed": [1, 2],
        "Freed Spike": [1],
        "Freed+": [2],
        "Grace": [1],
        "HR-V": [1],
        "Horizon": [1],
        "Insight": [1, 2],
        "Inspire": [1, 2, 3, 4, 5],
        "Integra": [1, 2, 3, 4],
        "Integra SJ": [1],
        "Jade": [1],
        "Jazz": [1, 2, 3],
        "Lagreat": [1],
        "Legend": [1, 2, 3, 4],
        "Life": [2, 3, 4, 5],
        "Life Dunk": [3],
        "Logo": [1],
        "MDX": [1],
        "Mobilio": [1],
        "Mobilio Spike": [1],
        "N-BOX": [1, 2],
        "N-BOX Slash": [1],
        "N-BOX+": [1],
        "N-ONE": [1, 2],
        "N-VAN": [1],
        "N-WGN": [1, 2],
        "Odyssey": [1, 2, 3, 4, 5],
        "Orthia": [1],
        "Partner": [1, 2],
        "Passport": [1, 2],
        "Pilot": [1, 2],
        "Prelude": [1, 2, 3, 4, 5],
        "Rafaga": [1],
        "Ridgeline": [1],
        "S-MX": [1],
        "S2000": [1],
        "S660": [1],
        "Saber": [1, 2],
        "Shuttle": [1, 2],
        "Stepwgn": [1, 2, 3, 4, 5],
        "Stream": [1, 2],
        "Street": [2],
        "That's": [1],
        "Today": [1, 2],
        "Torneo": [1],
        "Vamos": [2],
        "Vamos Hobio": [1],
        "Vezel": [1],
        "Vigor": [2, 3],
        "Z": [2],
        "Zest": [1],
        "e": [2],
    },
    "Hyundai": {
        "Accent": [1, 2, 3, 4, 5],
        "Atos": [1],
        "Avante": [1, 2, 3, 4, 5, 6],
        "Azera": [1, 2],
        "Centennial": [1],
        "Click": [1, 2, 4],
        "Coupe": [1, 2],
        "Creta": [1, 2],
        "Dynasty": [1, 2, 3, 4],
        "Elantra": [1, 2, 3, 4, 5, 6, 7],
        "Equus": [1, 2],
        "Excel": [1],
        "Galloper": [1, 2],
        "Genesis": [1, 2],
        "Getz": [1],
        "Grace": [1],
        "Grand Santa Fe": [1],
        "Grand Starex": [2],
        "Grandeur": [2, 3, 4, 5, 6],
        "H1": [1, 2],
        "H200": [1],
        "Ioniq": [1],
        "Kona": [1],
        "Lantra": [1, 2],
        "Lavita": [1],
        "Marcia": [1, 2, 3],
        "Matrix": [1],
        "NF": [1, 5],
        "Palisade": [1],
        "S Coupe": [1],
        "Santa Fe": [1, 2, 3, 4],
        "Santa Fe Classic": [1],
        "Santamo": [1, 2, 3, 4, 5, 6],
        "Scoupe": [1],
        "Solaris": [1, 2],
        "Sonata": [2, 3, 4, 5, 6, 7, 8],
        "Starex": [1, 2],
        "Stellar": [1],
        "Tager": [1, 4],
        "Terracan": [1],
        "Tiburon": [1, 2],
        "Trajet": [1],
        "Tucson": [1, 2, 3, 4],
        "Tuscani": [1, 2],
        "Veloster": [1, 2],
        "Veracruz": [1],
        "Verna": [1, 2, 4],
        "XG": [1],
        "i10": [1, 2],
        "i20": [1, 2],
        "i30": [1, 2, 3],
        "i40": [1],
        "ix20": [1, 2],
        "ix35": [1],
        "ix55": [1],
    },
    "Infiniti": {
        "EX25": [1],
        "EX30d": [2],
        "EX35": [1],
        "EX37": [1],
        "FX30d": [2],
        "FX35": [1, 2],
        "FX37": [2],
        "FX45": [1],
        "FX50": [2],
        "G20": [2],
        "G25": [4],
        "G35": [3, 4],
        "G37": [4],
        "I30": [1, 2],
        "I35": [1],
        "J30": [1],
        "JX35": [1],
        "M25": [4],
        "M35": [3],
        "M35 Hybrid": [3],
        "M37": [4],
        "M45": [2, 3],
        "M56": [4],
        "Q30": [4],
        "Q45": [1, 2, 3],
        "Q50": [4],
        "Q70": [1],
        "QX4": [1],
        "QX50": [1, 2],
        "QX56": [1, 2],
        "QX60": [1],
        "QX70": [2],
        "QX80": [1],
    },
    "Jaguar": {
        "E-Pace": [1],
        "F-Pace": [1],
        "S-type": [1],
        "Sovereign": [2],
        "X-Type": [1],
        "XE": [1],
        "XF": [1, 2],
        "XJ": [1, 3, 4, 8, 9],
        "XJS": [1],
        "XK": [1, 2],
    },
    "Jeep": {
        "Cherokee": [1, 2, 3, 4, 5],
        "Commander": [1],
        "Compass": [1, 2],
        "Grand Cherokee": [1, 2, 3, 4],
        "Grand Wagoneer": [2],
        "Jeep": [1],
        "Liberty": [1, 2],
        "Patriot": [1],
        "Renegade": [1],
        "Wagoneer": [1],
        "Wrangler": [1, 2, 3],
    },
    "Kia": {
        "Avella": [1],
        "Besta": [1],
        "Borrego": [1, 2],
        "Capital": [1],
        "Carens": [1, 2, 3],
        "Carnival": [1, 2, 3, 4],
        "Ceed": [1, 2, 3],
        "Cerato": [1, 2, 3, 4],
        "Cerato Koup": [1, 2],
        "Clarus": [1],
        "Credos": [1],
        "Enterprise": [1],
        "Forte": [1, 2, 3],
        "Grand Carnival": [1],
        "Joice": [1, 2],
        "K3": [1, 3],
        "K4": [1],
        "K5": [1, 2, 3],
        "K7": [1, 2],
        "K900": [2],
        "Lotze": [2],
        "Magentis": [1, 2],
        "Mohave": [1],
        "Morning": [1, 2, 3],
        "Opirus": [1],
        "Optima": [1, 2, 3, 4],
        "Picanto": [1, 2, 3],
        "Potentia": [1],
        "Pregio": [1],
        "Pride": [1, 2, 3],
        "ProCeed": [1, 2],
        "Quoris": [1],
        "Ray": [1, 3],
        "Retona": [1],
        "Rio": [1, 2, 3, 4],
        "Rio X (X-Line)": [1],
        "Sedona": [1],
        "Seltos": [1],
        "Sephia": [1, 2],
        "Shuma": [1, 2],
        "Sorento": [1, 2, 3, 4],
        "Soul": [1, 2, 3],
        "Spectra": [1, 2],
        "Sportage": [1, 2, 3, 4],
        "Stinger": [1],
        "Stonic": [1],
        "Towner": [1],
        "Venga": [1],
        "Visto": [1, 2],
        "X-Trek": [1, 2],
    },
    "Land": {
        "Rover Defender": [1],
        "Rover Discovery": [1, 2, 3, 4, 5],
        "Rover Discovery Sport": [1],
        "Rover Freelander": [1, 2],
        "Rover Land Rover": [2, 3],
        "Rover Range Rover": [1, 2, 3, 4],
        "Rover Range Rover Evoque": [1],
        "Rover Range Rover Sport": [1, 2],
        "Rover Series III": [1],
    },
    "Lexus": {
        "CT200h": [1],
        "ES200": [6],
        "ES250": [2, 6],
        "ES300": [2, 3, 4],
        "ES300h": [6],
        "ES330": [4],
        "ES350": [5, 6],
        "GS250": [4],
        "GS300": [1, 2, 3],
        "GS350": [3, 4],
        "GS400": [2],
        "GS430": [2, 3],
        "GS450h": [3, 4],
        "GS460": [3],
        "GX460": [2],
        "GX470": [1],
        "HS250h": [1],
        "IS F": [2],
        "IS200": [1],
        "IS220d": [2],
        "IS250": [2, 3],
        "IS300": [1, 2],
        "IS300h": [3],
        "IS350": [2],
        "IS350C": [2],
        "LS400": [1, 2],
        "LS430": [3],
        "LS460": [4],
        "LS460L": [4],
        "LS600h": [4],
        "LS600hL": [4],
        "LX450": [1],
        "LX470": [2],
        "LX570": [3],
        "NX200": [1],
        "NX200t": [1],
        "NX300": [1],
        "NX300h": [1],
        "RX200t": [4],
        "RX270": [3],
        "RX300": [1, 2],
        "RX330": [2],
        "RX350": [2, 3],
        "RX400h": [2],
        "RX450h": [3],
        "RX450h+": [5],
        "SC300": [1],
        "SC400": [1],
        "SC430": [2],
        "UX250h": [1],
    },
    "Lotus": {"Elise": [2]},
    "Mazda": {
        "121": [1, 2, 3],
        "323": [1, 2, 3, 4, 5, 6],
        "323C": [1],
        "323F": [1, 2, 6],
        "616": [1],
        "626": [1, 2, 3, 4, 5],
        "929": [3, 4, 5],
        "AZ-Offroad": [1],
        "AZ-Wagon": [2, 3, 4],
        "Atenza": [1, 2, 3],
        "Autozam AZ-1": [1],
        "Autozam AZ-3": [1],
        "Autozam Clef": [1],
        "Autozam Revue": [1],
        "Axela": [1, 2, 3],
        "B-Series": [4, 5],
        "BT-50": [1],
        "Biante": [1],
        "Bongo": [1, 2, 3, 4],
        "Bongo Brawny": [3, 4],
        "Bongo Friendee": [1],
        "CX-3": [1],
        "CX-5": [1, 2],
        "CX-7": [1],
        "CX-8": [1],
        "CX-9": [1, 2],
        "Capella": [3, 4, 5, 6, 7],
        "Carol": [2, 4, 5, 6, 7, 8],
        "Cosmo": [3],
        "Cronos": [1],
        "Demio": [1, 2, 3, 4],
        "Efini MPV": [1],
        "Efini MS-6": [1],
        "Efini MS-8": [1],
        "Efini MS-9": [5],
        "Efini RX-7": [3],
        "Eunos 100": [1],
        "Eunos 300": [1],
        "Eunos 500": [1],
        "Eunos 800": [1],
        "Eunos Cargo": [1],
        "Eunos Cosmo": [1],
        "Eunos Presso": [1],
        "Eunos Roadster": [1],
        "Familia": [4, 5, 6, 7, 8, 9, 10, 11],
        "Familia S-Wagon": [9],
        "Flair": [1, 2],
        "Flair Crossover": [1, 2],
        "Flair Wagon": [1, 2, 3],
        "Lantis": [1],
        "Laputa": [1],
        "Luce": [3, 4, 5],
        "MPV": [1, 2, 3],
        "MX-3": [1],
        "MX-30": [1],
        "MX-5": [1, 2, 3],
        "MX-6": [1, 2],
        "Mazda2": [1, 2, 3],
        "Mazda3": [1, 2, 3, 4],
        "Mazda3 MPS": [1, 2],
        "Mazda5": [2, 3],
        "Mazda6": [1, 2, 3],
        "Mazda6 MPS": [1],
        "Millenia": [1],
        "Persona": [1],
        "Premacy": [1, 2, 3],
        "Proceed": [1, 3],
        "Proceed Levante": [1, 2],
        "Proceed Marvie": [1],
        "Protege": [2, 3],
        "Protege5": [1, 3, 5],
        "RX-7": [3],
        "RX-8": [1],
        "Revue": [1],
        "Roadster": [1, 2, 3, 4],
        "Savanna RX-7": [2],
        "Scrum": [3, 4, 5],
        "Sentia": [1, 2],
        "Spiano": [1],
        "Tribute": [1, 2],
        "Verisa": [1],
        "Xedos 6": [1],
        "Xedos 9": [1],
    },
    "Mercedes-Benz": {
        "190": [1],
        "A-Class": [1, 2, 3, 4],
        "B-Class": [1, 2],
        "C-Class": [1, 2, 3, 4],
        "CL-Class": [1, 2, 3],
        "CLA-Class": [1, 2],
        "CLC-Class": [1],
        "CLK-Class": [1, 2],
        "CLS-Class": [1, 2],
        "Citan": [1],
        "E-Class": [1, 2, 3, 4, 5],
        "G-Class": [1, 2],
        "GL-Class": [1, 2],
        "GLA-Class": [1],
        "GLC": [1],
        "GLC Coupe": [1],
        "GLE": [1],
        "GLE Coupe": [1],
        "GLK-Class": [1],
        "M-Class": [1, 2, 3],
        "ML-Class": [2],
        "Mercedes": [1, 2, 3],
        "R-Class": [1],
        "S-Class": [1, 2, 3, 4, 5, 6],
        "SL-Class": [3, 4, 5],
        "SLK-Class": [1, 2, 3],
        "V-Class": [1, 2],
        "Vaneo": [1],
        "Viano": [2],
        "Vito": [1, 2, 3],
        "W115": [1],
        "W123": [1],
        "W180": [1],
        "X-Class": [2],
    },
    "Mitsubishi": {
        "3000GT": [1, 2],
        "ASX": [1],
        "Airtrek": [1],
        "Aspire": [1],
        "Attrage": [1],
        "Bravo": [2],
        "Carisma": [1],
        "Celeste": [1],
        "Challenger": [1],
        "Chariot": [1, 2],
        "Chariot Grandis": [1],
        "Colt": [2, 3, 4, 5, 6],
        "Colt Plus": [6],
        "Debonair": [1, 2, 3],
        "Delica": [1, 2, 3, 4, 5],
        "Delica D:2": [1, 2, 3],
        "Delica D:3": [1],
        "Delica D:5": [1],
        "Diamante": [1, 2],
        "Dion": [1],
        "Eclipse": [1, 2, 3, 4],
        "Eclipse Cross": [1],
        "Emeraude": [1],
        "Endeavor": [1],
        "Eterna": [1, 3, 4, 5],
        "Expo": [1],
        "FTO": [1],
        "Freeca": [1],
        "GTO": [1],
        "Galant": [3, 4, 5, 6, 7, 8, 9],
        "Galant Fortis": [1],
        "Grandis": [1],
        "Grunder": [1],
        "Jeep": [1],
        "L200": [2, 3, 4, 5],
        "L300": [2],
        "L400": [1],
        "Lancer": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "Lancer Cedia": [9],
        "Lancer Evolution": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "Legnum": [1],
        "Libero": [1],
        "Magna Wagon": [1],
        "Mighty Max": [2],
        "Minica": [6, 7, 8],
        "Minica Toppo": [2],
        "Minicab": [3, 4, 6, 7, 8],
        "Minicab MiEV": [1],
        "Mirage": [1, 2, 3, 4, 5, 6],
        "Mirage Dingo": [1],
        "Montero": [1, 2, 3],
        "Montero Sport": [1],
        "Nativa": [3, 4],
        "Outlander": [1, 2, 3],
        "Outlander Sport": [1],
        "Pajero": [1, 2, 3, 4],
        "Pajero Junior": [1],
        "Pajero Mini": [1, 2],
        "Pajero Pinin": [1],
        "Pajero Sport": [1, 2, 3],
        "Pajero iO": [1],
        "Proudia": [2],
        "RVR": [1, 2, 3],
        "Rosa": [1, 2, 7],
        "Sigma": [1],
        "Space Gear": [1],
        "Space Runner": [1, 2],
        "Space Star": [1, 2],
        "Space Wagon": [1, 2, 3],
        "Starion": [1],
        "Strada": [1, 2],
        "Toppo": [1],
        "Toppo BJ": [1],
        "Toppo BJ Wide": [1],
        "Town Box": [1, 2],
        "Town Box Wide": [1],
        "Towny": [3],
        "Tredia": [1],
        "Triton": [4],
        "eK Active": [1],
        "eK Space": [1, 2],
        "eK Sport": [1, 2],
        "eK Wagon": [1, 2, 3, 4],
        "eK X": [1],
        "eK classy": [1],
        "ek Custom": [1],
        "i": [1, 2, 3, 4, 6, 8],
        "i-MiEV": [1],
    },
    "Nissan": {
        "100NX": [1],
        "180SX": [1],
        "200SX": [4, 5, 6],
        "240SX": [1, 2],
        "300ZX": [1, 2],
        "350Z": [5],
        "370Z": [6],
        "AD": [1, 2, 3, 4],
        "Almera": [1, 2, 3],
        "Almera Classic": [1],
        "Altima": [1, 2, 3, 4, 5],
        "Armada": [1],
        "Auster": [1, 3],
        "Avenir": [1, 2],
        "Avenir Salut": [1, 2],
        "Bassara": [1],
        "Bluebird": [1, 2, 6, 7, 8, 9, 10],
        "Bluebird Maxima": [2],
        "Bluebird Sylphy": [1, 2],
        "Caravan": [1, 2, 3, 4, 5],
        "Caravan Elgrand": [1],
        "Cedric": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "Cedric Cima": [1],
        "Cefiro": [1, 2, 3, 4],
        "Cima": [2, 3, 4, 5],
        "Clipper": [1, 2],
        "Crew": [1],
        "Cube": [1, 2, 3],
        "Cube Cubic": [2],
        "DAYZ": [1, 2],
        "DAYZ Roox": [1],
        "Datsun": [7, 8, 9, 10],
        "Dualis": [1],
        "Elgrand": [1, 2, 3],
        "Exa": [1, 2],
        "Expert": [1],
        "Fairlady Z": [3, 4, 5],
        "Figaro": [1],
        "Frontier": [1, 2],
        "Fuga": [1, 2],
        "Gloria": [1, 5, 6, 7, 8, 9, 10, 11],
        "Gloria Cima": [1],
        "Homy": [1, 3, 4],
        "Homy Elgrand": [1],
        "Juke": [1, 2],
        "Kicks": [1],
        "King Cab": [1, 2, 4, 9],
        "Kix": [1],
        "Lafesta": [1, 2],
        "Langley": [2, 3],
        "Largo": [1, 2, 3],
        "Latio": [1],
        "Laurel": [2, 3, 4, 5, 6, 7, 8],
        "Laurel Spirit": [1, 2],
        "Leaf": [1, 2],
        "Leopard": [1, 2, 3, 4],
        "Liberta Villa": [1, 2],
        "Liberty": [1],
        "Lucino": [1],
        "March": [1, 2, 3, 4],
        "March Box": [2],
        "Maxima": [2, 3, 4, 5, 6, 7],
        "Micra": [1, 2, 3, 4, 5],
        "Micra C+C": [3],
        "Mistral": [1],
        "Moco": [1, 2, 3],
        "Murano": [1, 2, 3],
        "NP300": [1],
        "NV100 Clipper": [1, 2, 3],
        "NV150 AD": [1, 2, 3, 4],
        "NV200": [1],
        "NV350 Caravan": [5],
        "NX-Coupe": [1],
        "Navara": [1, 2],
        "Note": [1, 2, 3],
        "Otti": [1, 2],
        "Pathfinder": [1, 2, 3, 4],
        "Patrol": [2, 3, 4, 5, 6],
        "Pickup": [1],
        "Pino": [1],
        "Pixo": [1],
        "Prairie": [1, 2],
        "Prairie Joy": [2],
        "Presage": [1, 2],
        "Presea": [1, 2],
        "President": [2, 3, 4],
        "Primastar": [1],
        "Primera": [1, 2, 3],
        "Primera Camino": [2],
        "Pulsar": [2, 3, 4, 5, 6],
        "Qashqai": [1, 2],
        "Qashqai+2": [1],
        "Quest": [1, 2, 3, 4],
        "R'nessa": [1],
        "Rasheen": [1],
        "Rogue": [1, 2],
        "Roox": [1, 2],
        "S-Cargo": [1],
        "Safari": [1, 2, 3],
        "Sentra": [1, 3, 4, 5, 6, 7],
        "Serena": [1, 2, 3, 4, 5],
        "Silvia": [3, 4, 5, 6, 7],
        "Skyline": [5, 6, 7, 8, 9, 10, 11, 12, 13],
        "Skyline Crossover": [12],
        "Skyline GT-R": [8, 9, 10],
        "Stagea": [1, 2],
        "Stanza": [2, 3],
        "Sunny": [1, 2, 4, 5, 6, 7, 8, 9, 10],
        "Sunny California": [2, 3, 4],
        "Sunny RZ-1": [6],
        "Sylphy": [3],
        "Teana": [1, 2, 3],
        "Terra": [1],
        "Terrano": [1, 2, 3],
        "Terrano II": [1],
        "Terrano Regulus": [1],
        "Tiida": [1, 2],
        "Tiida Latio": [1],
        "Tino": [1],
        "Titan": [1],
        "Urvan": [1, 2],
        "Vanette": [1, 2, 3, 4],
        "Vanette Serena": [1],
        "Versa": [1, 2],
        "Violet": [2, 3],
        "Wingroad": [1, 2, 3],
        "X-Trail": [1, 2, 3],
        "Xterra": [1, 2],
        "e-NV200": [1],
    },
    "Peugeot": {
        "1007": [1],
        "106": [1],
        "107": [1],
        "108": [1],
        "2008": [1, 2],
        "205": [1],
        "206": [1],
        "207": [1],
        "208": [1, 2],
        "3008": [1, 2],
        "301": [1],
        "306": [1],
        "307": [1],
        "308": [1, 2],
        "309": [1],
        "4007": [1],
        "4008": [1],
        "405": [1],
        "406": [1],
        "407": [1],
        "408": [1],
        "5008": [1, 2],
        "508": [1, 2],
        "605": [1],
        "607": [1],
        "806": [1],
        "807": [1],
        "Bipper": [1],
        "Expert": [1, 2, 3],
        "Partner": [1, 2],
        "Partner Origin": [1],
        "Partner Tepee": [1, 2],
        "Peugeot": [1, 2],
        "RCZ": [1],
        "Traveller": [1],
    },
    "Porsche": {
        "911": [5],
        "924": [1],
        "928": [1],
        "944": [1],
        "Boxster": [1, 2],
        "Cayenne": [1, 2, 3],
        "Cayman": [1],
        "Macan": [1],
        "Panamera": [1],
    },
    "Renault": {
        "11": [1],
        "19": [1],
        "21": [1],
        "25": [1],
        "4": [1],
        "Arkana": [1],
        "Avantime": [1],
        "Captur": [1, 2],
        "Clio": [1, 2, 3, 4, 5],
        "Dokker": [1],
        "Dokker Stepway": [1],
        "Duster": [1, 2],
        "Espace": [1, 2, 3, 4, 5],
        "Fluence": [1],
        "Fluence Z.E.": [1],
        "Grand Scenic": [1, 2, 3],
        "Kadjar": [1],
        "Kangoo": [1, 2],
        "Kaptur": [1],
        "Koleos": [1, 2],
        "Laguna": [1, 2, 3],
        "Latitude": [1],
        "Lodgy": [1],
        "Logan": [1, 2],
        "Logan Stepway": [1],
        "Lutecia": [4],
        "Megane": [1, 2, 3, 4],
        "Modus": [1],
        "R5": [2],
        "R9": [1],
        "Rapid": [1, 2],
        "Renault": [1, 2],
        "Safrane": [1],
        "Samsung QM5": [1, 3],
        "Samsung SM3": [3],
        "Samsung SM3 Z.E.": [1],
        "Samsung SM5": [2],
        "Sandero": [1, 2],
        "Sandero Stepway": [1, 2],
        "Scenic": [1, 2, 3, 4],
        "Scenic RX4": [1],
        "Symbol": [1, 2],
        "Talisman": [1],
        "Trafic": [2, 3],
        "Twingo": [1, 2, 3],
        "Twizy": [1],
        "Vel Satis": [1],
        "Wind": [1],
        "ZOE": [1],
    },
    "Rolls-Royce": {"Silver Spur": [1]},
    "Skoda": {
        "Citigo": [1],
        "Fabia": [1, 2, 3],
        "Favorit": [1],
        "Felicia": [1],
        "Forman": [1],
        "Karoq": [1],
        "Kodiaq": [1],
        "Octavia": [1, 2, 3, 4],
        "Praktik": [1],
        "Rapid": [1, 2],
        "Roomster": [1],
        "Skoda": [1, 2],
        "Superb": [1, 2, 3],
        "Yeti": [1],
    },
    "Subaru": {
        "1300": [2, 3],
        "1600": [1],
        "1800": [3],
        "Alcyone": [1, 2],
        "B9 Tribeca": [1],
        "BRZ": [1],
        "Baja": [1, 3],
        "Bistro": [3],
        "Chiffon": [1, 2],
        "Crosstrek": [1],
        "Dex": [1],
        "Dias Wagon": [1],
        "Domingo": [1, 2],
        "Exiga": [1],
        "Exiga Crossover 7": [1],
        "Forester": [1, 2, 3, 4, 5],
        "Impreza": [1, 2, 3, 4, 5],
        "Impreza WRX": [1, 2, 3, 4],
        "Impreza WRX STI": [1, 2, 3],
        "Impreza XV": [1, 3],
        "Justy": [1, 2, 3, 4, 5],
        "Legacy": [1, 2, 3, 4, 5, 6],
        "Legacy B4": [3, 4, 5, 6],
        "Legacy Lancaster": [1, 2],
        "Leone": [1, 2, 3],
        "Levorg": [1, 2],
        "Libero": [1, 2],
        "Lucra": [1],
        "Outback": [1, 2, 3, 4, 5],
        "Pleo": [1, 2],
        "Pleo Nesta": [1],
        "Pleo Plus": [1, 2],
        "R1": [1],
        "R2": [1],
        "Rex": [3],
        "SVX": [1],
        "Sambar": [5, 6, 7],
        "Stella": [1, 2, 3],
        "Traviq": [1],
        "Trezia": [1],
        "Tribeca": [1],
        "Vivio": [1],
        "WRX STI": [1, 2, 3],
        "XT": [3],
        "XV": [1, 2, 3],
    },
    "Suzuki": {
        "Aerio": [1],
        "Alto": [1, 2, 3, 5, 6, 7, 8, 9],
        "Alto Lapin": [1, 2, 3],
        "Baleno": [1, 2, 3],
        "Cappuccino": [1],
        "Carry Van": [9],
        "Celerio": [1, 3],
        "Cervo": [2, 4, 5],
        "Cultus": [2, 3],
        "Cultus Crescent": [1, 2, 3],
        "Equator": [2],
        "Escudo": [1, 2, 3, 4],
        "Esteem": [1],
        "Every": [2, 3, 4, 5, 6],
        "Forenza": [1],
        "Grand Escudo": [1],
        "Grand Vitara": [1, 2],
        "Grand Vitara XL-7": [1],
        "Hustler": [1, 2],
        "Ignis": [1, 2],
        "Jimny": [1, 2, 3, 4],
        "Jimny Sierra": [2, 3, 4],
        "Jimny Wide": [3],
        "Join": [1],
        "Kei": [1],
        "Kizashi": [1],
        "Landy": [1, 2, 3],
        "Lapin": [1, 2, 3],
        "Liana": [1],
        "MR Wagon": [1, 2, 3],
        "Mighty Boy": [1],
        "Palette": [1],
        "SX4": [1, 2],
        "Samurai": [1, 2],
        "Sidekick": [1],
        "Solio": [1, 2, 3, 4],
        "Spacia": [1, 2],
        "Splash": [1],
        "Swift": [1, 2, 3, 4, 5],
        "Swift+": [1],
        "Twin": [1],
        "Verona": [1],
        "Vitara": [1, 2, 4],
        "Wagon R": [1, 2, 3, 4, 5, 6],
        "Wagon R Plus": [1, 2],
        "Wagon R Solio": [2],
        "Wagon R Wide": [1],
        "X-90": [1],
        "XL7": [2],
        "Xbee": [1],
    },
    "Toyota": {
        "2000GT": [1],
        "4Runner": [1, 2, 3, 4, 5],
        "Allex": [1],
        "Allion": [1, 2],
        "Alphard": [1, 2],
        "Altezza": [1],
        "Aqua": [1, 2],
        "Aristo": [1, 2],
        "Auris": [1, 2],
        "Avalon": [1, 2, 3],
        "Avanza": [2],
        "Avensis": [1, 2, 3],
        "Avensis Verso": [2],
        "Aygo": [1, 2],
        "Belta": [1],
        "Blade": [1],
        "Blizzard": [1, 2],
        "Brevis": [1],
        "C-HR": [1],
        "COMS": [1],
        "Caldina": [1, 2, 3],
        "Cami": [1],
        "Camry": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "Camry Gracia": [1],
        "Camry Prominent": [2, 3],
        "Carina": [1, 2, 3, 4, 5, 6, 7],
        "Carina E": [2, 3, 6],
        "Carina ED": [1, 2, 3],
        "Carina II": [5],
        "Cavalier": [1],
        "Celica": [2, 3, 4, 5, 6, 7],
        "Celsior": [1, 2, 3],
        "Century": [1, 2],
        "Chaser": [1, 2, 3, 4, 5, 6],
        "Comfort": [1],
        "Corolla": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        "Corolla Altis": [1],
        "Corolla Axio": [1, 2],
        "Corolla Ceres": [1],
        "Corolla FX": [1, 2, 3, 10, 11],
        "Corolla Fielder": [1, 2, 3],
        "Corolla II": [1, 2, 3, 4],
        "Corolla Levin": [3, 4, 5, 6, 7],
        "Corolla Rumion": [1],
        "Corolla Runx": [1],
        "Corolla Spacio": [1, 2],
        "Corolla Verso": [1, 2],
        "Corona": [1, 2, 5, 6, 7, 8, 9, 10],
        "Corona Exiv": [1, 2],
        "Corona Premio": [1],
        "Corona SF": [9, 10],
        "Corsa": [1, 2, 3, 4, 5, 7],
        "Cressida": [1, 2, 4],
        "Cresta": [1, 2, 3, 4, 5],
        "Crown": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "Crown Majesta": [1, 2, 3, 4, 5, 6],
        "Curren": [1],
        "Cynos": [1, 2],
        "Deliboy": [1],
        "Duet": [1],
        "Echo": [1],
        "Esquire": [1],
        "Estima": [1, 2, 3],
        "Estima Emina": [1],
        "Estima Lucida": [1],
        "FJ Cruiser": [1],
        "Fortuner": [1, 2],
        "Funcargo": [1],
        "GT 86": [1],
        "Gaia": [1],
        "Grand Hiace": [1],
        "Granvia": [1],
        "Harrier": [1, 2, 3],
        "Hiace": [1, 2, 3, 4, 5],
        "Hiace Regius": [1],
        "Highlander": [1, 2, 3],
        "Hilux": [1, 2, 3, 4, 5, 6, 7, 8],
        "Hilux Surf": [1, 2, 3, 4],
        "Innova": [2],
        "Ipsum": [1, 2],
        "Isis": [1],
        "Kluger V": [1],
        "Land Cruiser": [1, 2, 3, 5, 7, 8, 9, 10, 11],
        "Land Cruiser Cygnus": [1],
        "Land Cruiser Prado": [1, 2, 3, 4],
        "Levin": [5, 6, 7, 12],
        "Lite Ace": [1, 2, 3, 4, 5, 6],
        "Lite Ace Noah": [1],
        "MR-S": [3],
        "MR2": [1, 2, 3],
        "Mark II": [1, 3, 4, 5, 6, 7, 8, 9],
        "Mark II Wagon Blit": [1, 9],
        "Mark II Wagon Qualis": [1],
        "Mark X": [1, 2],
        "Mark X Zio": [1],
        "Master Ace Surf": [1],
        "Matrix": [1, 2],
        "Mega Cruiser": [1],
        "Mirai": [1],
        "Model F": [1],
        "Nadia": [1],
        "Noah": [1, 2, 3, 5],
        "Opa": [1],
        "Paseo": [2],
        "Passo": [1, 2, 3],
        "Passo Sette": [1],
        "Picnic": [1, 2],
        "Pixis Epoch": [1, 2],
        "Pixis Joy": [1],
        "Pixis Mega": [1],
        "Pixis Space": [1],
        "Pixis Van": [1],
        "Platz": [1],
        "Porte": [1, 2],
        "Premio": [1, 2],
        "Previa": [1, 2, 3],
        "Prius": [1, 2, 3, 4],
        "Prius Alpha": [1],
        "Prius C": [1],
        "Prius PHV": [3, 4],
        "Prius v": [1],
        "Probox": [1],
        "Progres": [1],
        "Pronard": [1],
        "RAV4": [1, 2, 3, 4, 5],
        "Ractis": [1, 2],
        "Raize": [1],
        "Raum": [1, 2],
        "Regius": [1],
        "Regius Ace": [1, 2],
        "Roomy": [1],
        "Rush": [1],
        "SD": [1],
        "SF": [9],
        "Sai": [1],
        "Scepter": [1],
        "Sequoia": [1, 2],
        "Sera": [1],
        "Sienna": [1, 2, 3],
        "Sienta": [1, 2, 3],
        "Soarer": [1, 2, 3, 4],
        "Solara": [1, 2],
        "Soluna": [5],
        "Spade": [1],
        "Sparky": [1],
        "Sprinter": [1, 2, 3, 4, 5, 6, 7, 8],
        "Sprinter Carib": [1, 2, 3],
        "Sprinter Marino": [1],
        "Sprinter Trueno": [4, 5, 6, 7],
        "Starlet": [2, 3, 4, 5],
        "Succeed": [1],
        "Supra": [3, 4],
        "T100": [1],
        "Tacoma": [1, 2],
        "Tank": [1],
        "Tercel": [1, 2, 3, 4, 5],
        "Touring Hiace": [1],
        "Town Ace": [1, 2, 3, 4, 5],
        "Town Ace Noah": [5],
        "Tundra": [1, 2],
        "Urban Cruiser": [1],
        "Vanguard": [1],
        "Vellfire": [1, 2],
        "Venza": [1],
        "Verossa": [1],
        "Verso": [1, 2],
        "Verso-S": [1],
        "Vios": [1, 2, 3],
        "Vista": [1, 2, 3, 4, 5],
        "Vista Ardeo": [1],
        "Vitz": [1, 2, 3],
        "Voltz": [1],
        "Voxy": [1, 2, 3],
        "WiLL Cypha": [1],
        "WiLL VS": [1],
        "WiLL Vi": [1],
        "Windom": [1, 2, 3],
        "Wish": [1, 2],
        "Yaris": [1, 2, 3, 4],
        "Yaris L": [3],
        "Yaris Verso": [1],
        "Yaris iA": [1],
        "bB": [1, 2],
        "iQ": [1],
        "ist": [1, 2],
        "xA": [1],
    },
    "Volkswagen": {
        "Amarok": [1],
        "Beetle": [1, 2],
        "Bora": [1],
        "Caddy": [1, 2, 3, 4],
        "California": [5],
        "Caravelle": [3, 4, 5],
        "Corrado": [1],
        "Country": [2, 4],
        "Derby": [2],
        "Eos": [1],
        "Fox": [1, 2, 3],
        "Golf": [1, 2, 3, 4, 5, 6, 7],
        "Golf Plus": [5],
        "Golf Sportsvan": [1],
        "Jetta": [1, 2, 3, 4, 5, 6, 7],
        "K70": [1],
        "Kaefer": [1, 5],
        "Lupo": [1],
        "Multivan": [4, 5],
        "Parati": [6],
        "Passat": [1, 2, 3, 4, 5, 6, 7, 8],
        "Passat CC": [1],
        "Phaeton": [1],
        "Pointer": [1],
        "Polo": [2, 3, 4, 5, 6],
        "Rabbit": [2],
        "Routan": [1, 5, 7],
        "Scirocco": [2, 3],
        "Sharan": [1, 2],
        "T-Cross": [1],
        "Taos": [1],
        "Taro": [2, 3, 4],
        "Teramont": [1],
        "Tiguan": [1, 2],
        "Touareg": [1, 2, 3],
        "Touran": [1, 2],
        "Transporter": [3, 4, 5, 6],
        "Vento": [1],
        "up!": [1, 4],
    },
    "Volvo": {
        "240": [1],
        "340": [1],
        "345": [1],
        "440": [1],
        "460": [1],
        "480": [1],
        "740": [1],
        "760": [1],
        "850": [1],
        "940": [1],
        "960": [1],
        "C30": [1],
        "C70": [1, 2, 3],
        "S40": [1, 2],
        "S60": [1, 2, 3],
        "S70": [1],
        "S80": [1, 2],
        "S90": [1],
        "T5": [1],
        "V40": [1, 2],
        "V50": [1],
        "V60": [1, 2],
        "V70": [1, 2, 3],
        "V90": [2],
        "Volvo": [1, 2],
        "XC40": [1],
        "XC60": [1, 2],
        "XC70": [2, 3],
        "XC90": [1],
    },
    "Лада": {
        "1111 Ока": [1],
        "2101": [1],
        "2102": [1],
        "2103": [1],
        "2104": [1],
        "2105": [1],
        "2106": [1],
        "2107": [1],
        "2108": [1],
        "2109": [1],
        "21099": [1],
        "2110": [1],
        "2111": [1],
        "2112": [1],
        "2113 Самара": [1],
        "2114 Самара": [1],
        "2115 Самара": [1],
        "2120 Надежда": [1],
        "2129": [1],
        "4x4 2121 Нива": [1],
        "4x4 2131 Нива": [1],
        "4x4 Бронто": [1],
        "4x4 Урбан": [1],
        "EL LADA": [1],
        "Samara": [1],
        "Веста": [1],
        "Веста Кросс": [1],
        "Веста Спорт": [1],
        "Гранта": [1],
        "Гранта Кросс": [1],
        "Гранта Спорт": [1],
        "Калина": [1, 2],
        "Калина Кросс": [1],
        "Калина Спорт": [1, 2],
        "Ларгус": [1],
        "Ларгус Кросс": [1],
        "Нива (2020-21 гг.)": [1],
        "Нива Бронто": [1],
        "Нива Легенд": [1],
        "Нива Пикап": [1],
        "Нива Тревел": [1],
        "Приора": [1],
        "Х-рей": [1],
        "Х-рей Кросс": [1],
    },
}
