brands_names = {
    "Audi": [
        "100",
        "200",
        "90",
        "80",
        "V8",
        "S4",
        "A4",
        "A8",
        "A6",
        "A3",
        "S8",
        "TT",
        "S6",
        "A6 allroad quattro",
        "Q7",
        "R8",
        "A5",
        "S5",
        "RS6",
        "Q5",
        "S3",
        "TTS",
        "A4 allroad quattro",
        "A7",
        "RS5",
        "A1",
        "RS3",
        "Q3",
        "RS Q3",
        "RS7",
        "SQ5",
        "Q2",
        "SQ7",
        "Q8",
        "Q3 Sportback",
        "SQ8",
        "SQ5 Sportback",
        "Q5 Sportback",
    ],
    "BMW": [
        "5-Series",
        "3-Series",
        "7-Series",
        "8-Series",
        "M5",
        "Z3",
        "X5",
        "M3",
        "X3",
        "6-Series",
        "Z4",
        "1-Series",
        "M6",
        "X6",
        "5-Series Gran Turismo",
        "X1",
        "4-Series",
        "3-Series Gran Turismo",
        "M4",
        "i3",
        "X4",
        "i8",
        "2-Series Active Tourer",
        "2-Series",
        "2-Series Gran Tourer",
        "M2",
        "X2",
        "6-Series Gran Turismo",
        "X7",
        "M8",
        "XM",
    ],
    "Cadillac": [
        "Fleetwood",
        "Seville",
        "DeVille",
        "Eldorado",
        "Escalade",
        "CTS",
        "SRX",
        "STS",
        "DTS",
        "BLS",
        "ATS",
        "ELR",
        "XT5",
        "CT6",
        "XT6",
        "XT4",
    ],
    "Changan": [
        "CS35",
        "CS75 Plus",
        "CS55",
        "CS35 Plus",
        "UNI-T",
        "UNI-K",
        "CS55 Plus",
        "UNI-V",
        "CS85 Coupe",
    ],
    "Chery": [
        "Amulet A15",
        "Tiggo T11",
        "QQ Sweet",
        "Oriental Son B11",
        "Fora A21",
        "Kimo A1",
        "QQ6 S21",
        "CrossEastar B14",
        "M11",
        "Very A13",
        "indiS S18D",
        "Bonus A13",
        "Tiggo 5",
        "Bonus 3 - A19",
        "Arrizo 7",
        "Tiggo 2",
        "Tiggo 3",
        "Tiggo 4",
        "Tiggo 7",
        "Tiggo 7 Pro",
        "Tiggo 8",
        "Tiggo 8 Pro",
        "Tiggo 8 Pro Max",
        "Tiggo 4 Pro",
        "Tiggo 7 Pro Max",
    ],
    "Chevrolet": [
        "Beretta",
        "Lumina",
        "Corvette",
        "Caprice",
        "Cavalier",
        "Astro",
        "Suburban",
        "Blazer",
        "Tahoe",
        "Camaro",
        "Tracker",
        "Alero",
        "MW",
        "Avalanche",
        "TrailBlazer",
        "Cruze",
        "Niva",
        "Aveo",
        "Lacetti",
        "Viva",
        "Evanda",
        "Lanos",
        "Spark",
        "HHR",
        "Rezzo",
        "Epica",
        "Captiva",
        "Equinox",
        "Volt",
        "Orlando",
        "Damas",
        "Cobalt",
        "Malibu",
        "Silverado",
        "Impala",
        "Trax",
        "Colorado",
        "Nexia",
        "Traverse",
    ],
    "Chrysler": [
        "Voyager",
        "New Yorker",
        "Intrepid",
        "Vision",
        "Concorde",
        "Neon",
        "Stratus",
        "Cirrus",
        "Grand Voyager",
        "Sebring",
        "300M",
        "LHS",
        "PT Cruiser",
        "Pacifica",
        "Crossfire",
        "300C",
        "Town and Country",
        "Ypsilon",
        "200",
    ],
    "Citroen": [
        "C15",
        "XM",
        "Xantia",
        "Jumpy",
        "Berlingo",
        "Xsara",
        "Xsara Picasso",
        "Saxo",
        "C5",
        "C3",
        "C2",
        "C4",
        "C1",
        "C4 Picasso",
        "Grand C4 Picasso",
        "C-Crosser",
        "Nemo",
        "C3 Picasso",
        "DS3",
        "DS4",
        "DS5",
        "C4 Aircross",
        "C-Elysee",
        "C4 Cactus",
        "Spacetourer",
        "C3 Aircross",
        "C5 Aircross",
    ],
    "Daewoo": [
        "Racer",
        "LeMans",
        "Prince",
        "Damas",
        "Tico",
        "Nexia",
        "Espero",
        "Nubira",
        "Lanos",
        "Leganza",
        "Matiz",
        "Magnus",
        "Tacuma",
        "Sens",
        "Lacetti",
        "Kalos",
        "Gentra",
        "Winstorm",
    ],
    "Daihatsu": [
        "Atrai",
        "Rocky",
        "Charade",
        "Delta",
        "Applause",
        "Pyzar",
        "Terios",
        "Mira",
        "Storia",
        "Terios Kid",
        "Cuore",
        "Charade Social",
        "YRV",
        "Atrai7",
        "Move",
        "Max",
        "Hijet",
        "Copen",
        "Mira Avy",
        "Boon",
        "Be-Go",
        "Sonica",
        "Esse",
        "Coo",
        "Tanto",
        "Boon Luminas",
        "Move Conte",
        "Tanto Exe",
        "Mira e:S",
        "Mebius",
        "Wake",
        "Cast",
        "Thor",
        "Altis",
        "Move Canbus",
        "Mira Tocot",
        "Taft",
    ],
    "Datsun": ["on-DO", "mi-Do"],
    "Dodge": [
        "Caravan",
        "Dynasty",
        "Spirit",
        "Stealth",
        "Intrepid",
        "Viper",
        "Neon",
        "Stratus",
        "Avenger",
        "Dakota",
        "Grand Caravan",
        "Ram",
        "Durango",
        "Magnum",
        "Charger",
        "Nitro",
        "Caliber",
        "Journey",
        "Challenger",
        "Dart",
    ],
    "Dongfeng": ["H30 Cross", "AX7", "580", "DF6"],
    "EXEED": ["TXL", "VX", "LX"],
    "FAW": ["Vita", "Besturn B50", "V5", "V2", "Oley", "Besturn X40", "Bestune T55"],
    "Fiat": [
        "Croma",
        "Panda",
        "Bravo",
        "Doblo",
        "Punto",
        "Grande Punto",
        "Linea",
        "500",
        "Scudo",
        "Fullback",
    ],
    "Ford": [
        "Sierra",
        "Escort",
        "Scorpio",
        "Orion",
        "Festiva",
        "Bronco",
        "Mustang",
        "Fiesta",
        "Telstar",
        "Explorer",
        "Taurus",
        "Mondeo",
        "F150",
        "Maverick",
        "Tourneo",
        "Spectron",
        "Freda",
        "Galaxy",
        "Ka",
        "Expedition",
        "Laser",
        "Puma",
        "Focus",
        "Cougar",
        "F250",
        "Excursion",
        "Ixion",
        "Escape",
        "Tourneo Connect",
        "Fusion",
        "C-MAX",
        "Focus ST",
        "S-MAX",
        "Ranger",
        "Edge",
        "Kuga",
        "Grand C-MAX",
        "EcoSport",
        "Tourneo Courier",
    ],
    "Geely": [
        "Otaka CK",
        "MK Cross",
        "MK",
        "Emgrand EC7",
        "Emgrand X7",
        "Atlas",
        "Tugella FY11",
        "Coolray SX11",
        "Atlas Pro",
        "Monjaro",
    ],
    "Genesis": ["G80", "G70", "G90", "GV80", "GV70"],
    "Great Wall": [
        "Safe",
        "Hover",
        "Wingle",
        "Hover H3",
        "Hover H5",
        "Hover M2",
        "Hover M4",
        "Hover H6",
        "Wingle 7",
        "Pao",
        "Poer",
    ],
    "Haval": ["H6", "H9", "H2", "F7", "F7x", "H5", "Jolion", "Dargo"],
    "Honda": [
        "Prelude",
        "Civic",
        "Accord",
        "City",
        "Civic Shuttle",
        "Legend",
        "Integra",
        "Concerto",
        "Vigor",
        "Accord Inspire",
        "Ascot",
        "Civic Ferio",
        "Today",
        "Ascot Innova",
        "Domani",
        "CR-X del Sol",
        "Inspire",
        "Rafaga",
        "Odyssey",
        "CR-V",
        "Saber",
        "Shuttle",
        "Orthia",
        "Partner",
        "Logo",
        "Integra SJ",
        "S-MX",
        "Stepwgn",
        "Torneo",
        "HR-V",
        "Capa",
        "Z",
        "Life",
        "Avancier",
        "Civic Type R",
        "Stream",
        "Fit",
        "Mobilio",
        "Fit Aria",
        "That's",
        "Mobilio Spike",
        "Pilot",
        "Jazz",
        "Element",
        "MDX",
        "Elysion",
        "Edix",
        "Ridgeline",
        "Airwave",
        "FR-V",
        "Zest",
        "Crossroad",
        "Vamos",
        "Freed",
        "Insight",
        "Crosstour",
        "CR-Z",
        "Freed Spike",
        "Fit Shuttle",
        "N-BOX",
        "Vamos Hobio",
        "N-ONE",
        "Acty",
        "N-WGN",
        "N-BOX+",
        "Vezel",
        "Grace",
        "N-BOX Slash",
        "Jade",
        "S660",
        "Freed+",
        "N-VAN",
    ],
    "Hyundai": [
        "Grace",
        "Lantra",
        "Elantra",
        "Sonata",
        "Galloper",
        "Grandeur",
        "S Coupe",
        "Accent",
        "Avante",
        "Coupe",
        "Tiburon",
        "Starex",
        "Atos",
        "H1",
        "XG",
        "Trajet",
        "Equus",
        "Santa Fe",
        "Matrix",
        "Terracan",
        "Getz",
        "Tucson",
        "NF",
        "Veracruz",
        "Santa Fe Classic",
        "i30",
        "i10",
        "Genesis",
        "i20",
        "ix35",
        "ix55",
        "Solaris",
        "Veloster",
        "i40",
        "Grand Santa Fe",
        "Creta",
        "Kona",
        "Palisade",
        "Venue",
        "Staria",
    ],
    "Infiniti": [
        "J30",
        "QX4",
        "Q45",
        "I30",
        "FX35",
        "G35",
        "FX45",
        "QX56",
        "M45",
        "M35",
        "FX37",
        "G37",
        "EX35",
        "FX50",
        "G25",
        "M37",
        "M25",
        "FX30d",
        "M56",
        "EX37",
        "EX25",
        "JX35",
        "QX70",
        "QX50",
        "QX80",
        "QX60",
        "Q50",
        "Q70",
        "Q30",
        "QX30",
        "Q60",
        "QX55",
    ],
    "Isuzu": [
        "Trooper",
        "Piazza",
        "Gemini",
        "Bighorn",
        "Fargo",
        "MU",
        "Pa Nero",
        "Rodeo",
        "Aska",
        "VehiCross",
        "Wizard",
        "Axiom",
        "D-MAX",
    ],
    "JAC": ["S1", "S5", "T6", "J7", "JS6", "JS4"],
    "Jaguar": [
        "XJ",
        "S-type",
        "X-Type",
        "XK",
        "XF",
        "F-Type",
        "XE",
        "E-Pace",
        "F-Pace",
    ],
    "Jeep": [
        "Wrangler",
        "Cherokee",
        "Grand Cherokee",
        "Liberty",
        "Compass",
        "Commander",
        "Patriot",
        "Renegade",
        "Gladiator",
        "Grand Wagoneer",
    ],
    "Kaiyi": ["E5"],
    "Kia": [
        "Besta",
        "Sephia",
        "Sportage",
        "Pregio",
        "Avella",
        "Clarus",
        "Shuma",
        "Carnival",
        "Rio",
        "Magentis",
        "Spectra",
        "Sorento",
        "Carens",
        "Picanto",
        "Opirus",
        "Optima",
        "Cerato",
        "Ceed",
        "ProCeed",
        "Soul",
        "Forte",
        "Cerato Koup",
        "K5",
        "Venga",
        "Pride",
        "Mohave",
        "Quoris",
        "K7",
        "K3",
        "Niro",
        "Stonic",
        "Rio X (X-Line)",
        "Stinger",
        "K900",
        "Seltos",
        "Xceed",
        "K9",
    ],
    "Land Rover": [
        "Discovery",
        "Defender",
        "Range Rover",
        "Freelander",
        "Range Rover Sport",
        "Range Rover Evoque",
        "Discovery Sport",
        "Range Rover Velar",
    ],
    "Lexus": [
        "LS400",
        "SC400",
        "GS300",
        "ES300",
        "LX450",
        "GS400",
        "RX300",
        "LX470",
        "IS200",
        "LS430",
        "GS430",
        "SC430",
        "GX470",
        "RX330",
        "IS300",
        "ES330",
        "RX400h",
        "IS250",
        "IS220d",
        "IS350",
        "GS350",
        "RX350",
        "ES350",
        "LS460",
        "GS450h",
        "LS460L",
        "LX570",
        "LS600hL",
        "LS600h",
        "RX450h",
        "GX460",
        "HS250h",
        "IS350C",
        "CT200h",
        "RX270",
        "IS250C",
        "ES250",
        "GS250",
        "ES300h",
        "IS300h",
        "GS300h",
        "NX200t",
        "NX300h",
        "NX200",
        "RC350",
        "RX200t",
        "RC300h",
        "RC200t",
        "LX450d",
        "IS200t",
        "ES200",
        "GS200t",
        "NX300",
        "RX450hL",
        "LC500h",
        "LC500",
        "LS500",
        "RX350L",
        "LS500h",
        "RC300",
        "UX200",
        "UX250h",
        "NX250",
        "LX600",
        "NX350h",
        "NX350",
        "LX500d",
        "RX500h",
        "RX350h",
    ],
    "Lifan": [
        "Breez",
        "Solano",
        "Smily",
        "X60",
        "Cebrium",
        "Celliya",
        "X50",
        "Myway",
        "Murman",
        "X70",
    ],
    "MINI": [
        "Hatch",
        "Clubman",
        "Cabrio",
        "Countryman",
        "Coupe",
        "Paceman",
        "Crossover",
    ],
    "Mazda": [
        "626",
        "Capella",
        "Cosmo",
        "Familia",
        "Luce",
        "323",
        "323F",
        "Bongo",
        "Persona",
        "Proceed",
        "Autozam AZ-3",
        "Cronos",
        "Sentia",
        "MX-3",
        "Proceed Marvie",
        "Efini MS-9",
        "Xedos 6",
        "Eunos 500",
        "Efini MS-8",
        "Efini MS-6",
        "Xedos 9",
        "Eunos Presso",
        "Lantis",
        "Protege",
        "MPV",
        "Proceed Levante",
        "Bongo Friendee",
        "Efini MPV",
        "Millenia",
        "Demio",
        "Eunos 800",
        "RX-7",
        "Familia S-Wagon",
        "Premacy",
        "AZ-Offroad",
        "Tribute",
        "Atenza",
        "Mazda6",
        "Mazda2",
        "B-Series",
        "Mazda3",
        "RX-8",
        "Axela",
        "Spiano",
        "Mazda5",
        "Verisa",
        "AZ-Wagon",
        "Mazda6 MPS",
        "Mazda3 MPS",
        "CX-7",
        "Carol",
        "BT-50",
        "MX-5",
        "CX-9",
        "Biante",
        "Roadster",
        "Scrum",
        "CX-5",
        "Flair",
        "Flair Wagon",
        "Flair Crossover",
        "CX-3",
        "CX-8",
        "CX-30",
        "CX-4",
        "MX-30",
        "CX-60",
    ],
    "Mercedes-Benz": [
        "S-Class",
        "190",
        "W123",
        "E-Class",
        "G-Class",
        "SL-Class",
        "CL-Class",
        "C-Class",
        "Vito",
        "SLK-Class",
        "V-Class",
        "M-Class",
        "CLK-Class",
        "A-Class",
        "Vaneo",
        "Viano",
        "CLS-Class",
        "R-Class",
        "B-Class",
        "GL-Class",
        "GLK-Class",
        "CLC-Class",
        "CLA-Class",
        "GLA-Class",
        "Citan",
        "AMG GT",
        "GLE",
        "GLC",
        "GLE Coupe",
        "GLS-Class",
        "GLC Coupe",
        "SLC-Class",
        "X-Class",
        "GLB-Class",
    ],
    "Mitsubishi": [
        "Tredia",
        "Pajero",
        "Space Wagon",
        "Lancer",
        "Debonair",
        "L200",
        "Galant",
        "L300",
        "Delica",
        "Mirage",
        "Eterna",
        "Chariot",
        "Eclipse",
        "Diamante",
        "Sigma",
        "GTO",
        "RVR",
        "Montero",
        "Space Runner",
        "Emeraude",
        "Libero",
        "Minica",
        "Colt",
        "Strada",
        "Lancer Evolution",
        "Pajero Mini",
        "L400",
        "FTO",
        "Pajero Junior",
        "Carisma",
        "Challenger",
        "Montero Sport",
        "Legnum",
        "Pajero Sport",
        "Chariot Grandis",
        "Space Gear",
        "Mirage Dingo",
        "Pajero iO",
        "Toppo BJ",
        "Space Star",
        "Aspire",
        "Pajero Pinin",
        "Toppo BJ Wide",
        "Town Box Wide",
        "Dion",
        "Lancer Cedia",
        "Airtrek",
        "eK Wagon",
        "Outlander",
        "eK Sport",
        "Grandis",
        "Endeavor",
        "Colt Plus",
        "Town Box",
        "i",
        "Delica D:5",
        "Toppo",
        "ASX",
        "Galant Fortis",
        "Delica D:2",
        "Delica D:3",
        "ek Custom",
        "eK Space",
        "Minicab",
        "Xpander",
        "Eclipse Cross",
    ],
    "Nissan": [
        "Patrol",
        "Pulsar",
        "Cherry",
        "Cedric",
        "Laurel",
        "Sunny",
        "Skyline",
        "Gloria",
        "Bluebird",
        "Sunny RZ-1",
        "Terrano",
        "Homy",
        "Laurel Spirit",
        "Cefiro",
        "Caravan",
        "Prairie",
        "Langley",
        "March",
        "Skyline GT-R",
        "300ZX",
        "Datsun",
        "Maxima",
        "200SX",
        "Fairlady Z",
        "Safari",
        "Pathfinder",
        "Cedric Cima",
        "Presea",
        "NX-Coupe",
        "Primera",
        "AD",
        "Silvia",
        "Sunny California",
        "100NX",
        "Avenir",
        "Vanette Serena",
        "Figaro",
        "Serena",
        "Gloria Cima",
        "180SX",
        "Leopard",
        "Largo",
        "Micra",
        "Terrano II",
        "Rasheen",
        "Mistral",
        "President",
        "Lucino",
        "Almera",
        "Avenir Salut",
        "Prairie Joy",
        "Primera Camino",
        "Wingroad",
        "Terrano Regulus",
        "Stagea",
        "Cima",
        "R'nessa",
        "Caravan Elgrand",
        "Elgrand",
        "Homy Elgrand",
        "Cube",
        "Tino",
        "Liberty",
        "Presage",
        "Sentra",
        "Expert",
        "Bassara",
        "Crew",
        "March Box",
        "Xterra",
        "Bluebird Sylphy",
        "X-Trail",
        "Frontier",
        "Altima",
        "Murano",
        "Moco",
        "350Z",
        "Teana",
        "Armada",
        "Titan",
        "Cube Cubic",
        "Quest",
        "Tiida Latio",
        "Fuga",
        "Tiida",
        "Lafesta",
        "Note",
        "Otti",
        "Almera Classic",
        "Navara",
        "Qashqai",
        "Dualis",
        "Pino",
        "Rogue",
        "Kix",
        "NP300",
        "Qashqai+2",
        "Clipper",
        "GT-R",
        "NV200",
        "Roox",
        "Skyline Crossover",
        "Pixo",
        "Juke",
        "Sylphy",
        "Latio",
        "370Z",
        "DAYZ",
        "NV100 Clipper",
        "DAYZ Roox",
        "NV350 Caravan",
        "Kicks",
    ],
    "OMODA": ["C5"],
    "Opel": [
        "Kadett",
        "Omega",
        "Vectra",
        "Calibra",
        "Astra",
        "Frontera",
        "Monterey",
        "Corsa",
        "Tigra",
        "Vita",
        "Zafira",
        "Combo",
        "Meriva",
        "Signum",
        "Astra GTC",
        "Antara",
        "Vivaro",
        "Insignia",
        "Astra Family",
        "Mokka",
        "Grandland X",
        "Zafira Life",
    ],
    "Peugeot": [
        "205",
        "405",
        "605",
        "309",
        "306",
        "406",
        "Expert",
        "Partner",
        "206",
        "607",
        "307",
        "807",
        "407",
        "1007",
        "207",
        "308",
        "107",
        "4007",
        "Partner Tepee",
        "Partner Origin",
        "5008",
        "3008",
        "RCZ",
        "408",
        "508",
        "4008",
        "208",
        "301",
        "2008",
        "Traveller",
    ],
    "Porsche": [
        "944",
        "928",
        "911",
        "Boxster",
        "Cayenne",
        "Cayman",
        "Panamera",
        "Macan",
        "Cayenne Coupe",
    ],
    "Renault": [
        "19",
        "25",
        "Espace",
        "Safrane",
        "Twingo",
        "Laguna",
        "Megane",
        "Scenic",
        "Kangoo",
        "Clio",
        "Symbol",
        "Scenic RX4",
        "Trafic",
        "Vel Satis",
        "Logan",
        "Grand Scenic",
        "Koleos",
        "Modus",
        "Sandero",
        "Fluence",
        "Duster",
        "Sandero Stepway",
        "Latitude",
        "Talisman",
        "Kaptur",
        "Kadjar",
        "Dokker",
        "Logan Stepway",
        "Arkana",
        "Dokker Stepway",
    ],
    "Skoda": [
        "Felicia",
        "Octavia",
        "Fabia",
        "Superb",
        "Roomster",
        "Yeti",
        "Rapid",
        "Kodiaq",
        "Karoq",
        "Scala",
    ],
    "SsangYong": [
        "Korando",
        "Korando Family",
        "Musso",
        "Chairman",
        "Rexton",
        "Musso Sports",
        "Actyon",
        "Kyron",
        "Actyon Sports",
        "Rodius",
        "Korando Sports",
        "Nomad",
        "Korando Turismo",
        "Tivoli",
        "Torres",
    ],
    "Subaru": [
        "Justy",
        "Domingo",
        "Legacy",
        "Leone",
        "Impreza",
        "Impreza WRX",
        "Impreza WRX STI",
        "SVX",
        "Outback",
        "Forester",
        "Legacy Lancaster",
        "Legacy B4",
        "Pleo",
        "Traviq",
        "Sambar",
        "R2",
        "B9 Tribeca",
        "R1",
        "Stella",
        "Dex",
        "Exiga",
        "Tribeca",
        "Dias Wagon",
        "Impreza XV",
        "Trezia",
        "Lucra",
        "XV",
        "BRZ",
        "Levorg",
        "Pleo Plus",
        "Chiffon",
        "Ascent",
        "Crosstrek",
    ],
    "Suzuki": [
        "Jimny",
        "Escudo",
        "Vitara",
        "Cultus",
        "Jimny Sierra",
        "Every",
        "Baleno",
        "X-90",
        "Swift",
        "Wagon R",
        "Grand Vitara",
        "Wagon R Wide",
        "Jimny Wide",
        "Kei",
        "Wagon R Plus",
        "Alto",
        "Wagon R Solio",
        "Grand Escudo",
        "Grand Vitara XL-7",
        "Ignis",
        "Aerio",
        "MR Wagon",
        "Liana",
        "Alto Lapin",
        "Solio",
        "SX4",
        "Cervo",
        "XL7",
        "Landy",
        "Splash",
        "Palette",
        "Kizashi",
        "Spacia",
        "Hustler",
        "Xbee",
        "Ertiga",
        "Ciaz",
    ],
    "Tank": ["500"],
    "Toyota": [
        "Celica",
        "Carina",
        "Soarer",
        "Corolla II",
        "Corona",
        "Corsa",
        "Sprinter Carib",
        "Corolla",
        "Mark II",
        "Land Cruiser",
        "Vista",
        "Crown",
        "Sprinter Trueno",
        "Corolla Levin",
        "Hilux",
        "Chaser",
        "Camry",
        "Corolla FX",
        "Hilux Surf",
        "Hiace",
        "Blizzard",
        "Starlet",
        "Model F",
        "Town Ace",
        "Carina ED",
        "Lite Ace",
        "4Runner",
        "Cresta",
        "Century",
        "Sprinter",
        "Supra",
        "Corona SF",
        "MR2",
        "Master Ace Surf",
        "Camry Prominent",
        "Corona Exiv",
        "Celsior",
        "Tercel",
        "Previa",
        "Land Cruiser Prado",
        "Estima",
        "Aristo",
        "Cynos",
        "Sera",
        "Windom",
        "Estima Emina",
        "Sprinter Marino",
        "Caldina",
        "Corolla Ceres",
        "Carina E",
        "Estima Lucida",
        "Crown Majesta",
        "Scepter",
        "RAV4",
        "Curren",
        "Avalon",
        "Cavalier",
        "Granvia",
        "Picnic",
        "Lite Ace Noah",
        "Town Ace Noah",
        "Ipsum",
        "Corona Premio",
        "Camry Gracia",
        "Corolla Spacio",
        "Avensis",
        "Mark II Wagon Qualis",
        "Harrier",
        "Raum",
        "Sienna",
        "Hiace Regius",
        "Prius",
        "Tacoma",
        "Gaia",
        "Altezza",
        "Vista Ardeo",
        "Duet",
        "Nadia",
        "Progres",
        "Land Cruiser Cygnus",
        "Solara",
        "Vitz",
        "Funcargo",
        "Platz",
        "Echo",
        "Yaris",
        "Grand Hiace",
        "Yaris Verso",
        "Cami",
        "Touring Hiace",
        "Tundra",
        "Regius",
        "Mega Cruiser",
        "Corolla Fielder",
        "Opa",
        "Kluger V",
        "Pronard",
        "WiLL Vi",
        "Corolla Altis",
        "bB",
        "Sequoia",
        "MR-S",
        "Sparky",
        "Highlander",
        "Verossa",
        "Allion",
        "Premio",
        "Noah",
        "WiLL VS",
        "Allex",
        "Corolla Runx",
        "Avensis Verso",
        "Voxy",
        "Brevis",
        "Corolla Verso",
        "Mark II Wagon Blit",
        "Voltz",
        "Succeed",
        "Alphard",
        "Probox",
        "WiLL Cypha",
        "ist",
        "Matrix",
        "Vios",
        "Wish",
        "Sienta",
        "Regius Ace",
        "Mark X",
        "Passo",
        "Porte",
        "Isis",
        "Belta",
        "Ractis",
        "Fortuner",
        "Aygo",
        "Corolla Axio",
        "Auris",
        "Blade",
        "FJ Cruiser",
        "Rush",
        "Corolla Rumion",
        "Vanguard",
        "Mark X Zio",
        "Vellfire",
        "iQ",
        "Passo Sette",
        "Venza",
        "Verso",
        "Sai",
        "Prius Alpha",
        "Aqua",
        "Pixis Space",
        "Spade",
        "GT 86",
        "Pixis Epoch",
        "Prius PHV",
        "Prius C",
        "Esquire",
        "Prius v",
        "C-HR",
        "Tank",
        "Roomy",
        "Pixis Joy",
        "Prius Prime",
        "Yaris iA",
        "Pixis Mega",
        "Raize",
        "GranAce",
        "Yaris Cross",
        "Corolla Cross",
        "GR 86",
    ],
    "Volkswagen": [
        "Golf",
        "Jetta",
        "Passat",
        "Multivan",
        "Vento",
        "Caravelle",
        "Polo",
        "Caddy",
        "Sharan",
        "Bora",
        "Beetle",
        "Lupo",
        "Touareg",
        "Phaeton",
        "Touran",
        "Pointer",
        "Golf Plus",
        "Eos",
        "Passat CC",
        "Tiguan",
        "Scirocco",
        "Transporter",
        "Amarok",
        "up!",
        "Arteon",
        "Tiguan Allspace",
        "Teramont",
        "California",
        "T-Cross",
        "Tiguan X",
        "Taos",
        "Teramont X",
    ],
    "Volvo": [
        "340",
        "440",
        "460",
        "960",
        "850",
        "480",
        "S40",
        "V40",
        "S90",
        "S70",
        "C70",
        "V90",
        "V70",
        "S80",
        "S60",
        "XC70",
        "XC90",
        "V50",
        "C30",
        "XC60",
        "V60",
        "XC40",
    ],
    "Vortex": ["Estina", "Tingo", "Corda"],
    "ГАЗ": [
        "3102 Волга",
        "24 Волга",
        "31029 Волга",
        "3110 Волга",
        "3111 Волга",
        "31105 Волга",
        "2330 Тигр",
        "Волга Сайбер",
    ],
    "ЗАЗ": ["Таврия", "Славута", "Сенс", "Шанс", "Вида"],
    "ИЖ": ["2125 Комби", "2715", "2126 Ода", "2717", "21261 Фабула"],
    "Лада": [
        "2107",
        "2104",
        "2108",
        "2105",
        "2106",
        "2109",
        "1111 Ока",
        "21099",
        "4x4 2131 Нива",
        "4x4 2121 Нива",
        "2110",
        "Нива Пикап",
        "4x4 Бронто",
        "2111",
        "2115 Самара",
        "2120 Надежда",
        "2112",
        "2114 Самара",
        "Калина",
        "2113 Самара",
        "Приора",
        "Калина Спорт",
        "Гранта",
        "Ларгус",
        "Гранта Спорт",
        "4x4 Урбан",
        "Калина Кросс",
        "Ларгус Кросс",
        "Веста",
        "Х-рей",
        "Веста Кросс",
        "Х-рей Кросс",
        "Веста Спорт",
        "Гранта Кросс",
        "Нива (2020-21 гг.)",
        "Нива Легенд",
        "Нива Тревел",
        "Нива Бронто",
    ],
    "Москвич": ["412", "2141", "2335", "3"],
    "УАЗ": ["3151", "3153", "Симбир", "3159", "Хантер", "Патриот", "Пикап"],
}
