names = [
    "5-Series",
    "S-Class",
    "3-Series",
    "3102 Волга",
    "Celica",
    "Patrol",
    "Carina",
    "Soarer",
    "2107",
    "412",
    "2125 Комби",
    "100",
    "2715",
    "Corolla II",
    "Corona",
    "626",
    "Corsa",
    "Sprinter Carib",
    "190",
    "Pulsar",
    "Tredia",
    "Sierra",
    "Corolla",
    "Mark II",
    "Cherry",
    "Land Cruiser",
    "Pajero",
    "Vista",
    "Cedric",
    "Prelude",
    "Laurel",
    "Golf",
    "Sunny",
    "Jetta",
    "Crown",
    "Skyline",
    "Gloria",
    "Sprinter Trueno",
    "Trooper",
    "Corolla Levin",
    "Civic",
    "Hilux",
    "Korando",
    "205",
    "7-Series",
    "W123",
    "Accord",
    "Escort",
    "200",
    "Capella",
    "2104",
    "2108",
    "Chaser",
    "Camry",
    "Justy",
    "Bluebird",
    "340",
    "24 Волга",
    "C15",
    "Corolla FX",
    "Hilux Surf",
    "Kadett",
    "90",
    "Hiace",
    "Blizzard",
    "Starlet",
    "Model F",
    "City",
    "Civic Shuttle",
    "2105",
    "2106",
    "3151",
    "E-Class",
    "Cosmo",
    "Scorpio",
    "Familia",
    "Town Ace",
    "Carina ED",
    "Lite Ace",
    "Besta",
    "Space Wagon",
    "4Runner",
    "Piazza",
    "Luce",
    "Legend",
    "944",
    "323",
    "Gemini",
    "Cresta",
    "Lancer",
    "Grace",
    "80",
    "Sunny RZ-1",
    "Terrano",
    "Omega",
    "2141",
    "Orion",
    "Festiva",
    "Domingo",
    "Racer",
    "LeMans",
    "Debonair",
    "Atrai",
    "L200",
    "928",
    "2109",
    "Century",
    "Galant",
    "Таврия",
    "Sprinter",
    "Jimny",
    "L300",
    "Supra",
    "Bighorn",
    "G-Class",
    "Rocky",
    "Homy",
    "Corona SF",
    "Caravan",
    "405",
    "MR2",
    "Integra",
    "Laurel Spirit",
    "Passat",
    "Cefiro",
    "Master Ace Surf",
    "Vectra",
    "Escudo",
    "Delica",
    "Vitara",
    "Concerto",
    "Wrangler",
    "440",
    "Prairie",
    "Cultus",
    "19",
    "460",
    "V8",
    "Korando Family",
    "Camry Prominent",
    "Langley",
    "Voyager",
    "Dynasty",
    "25",
    "Charade",
    "Bronco",
    "Delta",
    "New Yorker",
    "March",
    "Cherokee",
    "Spirit",
    "Mirage",
    "605",
    "Skyline GT-R",
    "300ZX",
    "Mustang",
    "Beretta",
    "Datsun",
    "8-Series",
    "Legacy",
    "Eterna",
    "1111 Ока",
    "Calibra",
    "Maxima",
    "Corona Exiv",
    "Fiesta",
    "200SX",
    "Chariot",
    "Vigor",
    "Accord Inspire",
    "Fairlady Z",
    "Leone",
    "Safari",
    "SL-Class",
    "Ascot",
    "Pathfinder",
    "323F",
    "Applause",
    "XM",
    "Telstar",
    "Lumina",
    "Discovery",
    "Cedric Cima",
    "LS400",
    "Celsior",
    "309",
    "21099",
    "Bongo",
    "960",
    "Tercel",
    "Previa",
    "Explorer",
    "Defender",
    "Presea",
    "NX-Coupe",
    "Land Cruiser Prado",
    "Primera",
    "Persona",
    "Eclipse",
    "Proceed",
    "2126 Ода",
    "AD",
    "Silvia",
    "Diamante",
    "Sunny California",
    "100NX",
    "Avenir",
    "Stealth",
    "Lantra",
    "Fleetwood",
    "Multivan",
    "Sigma",
    "Elantra",
    "GTO",
    "Estima",
    "Astra",
    "Civic Ferio",
    "Sonata",
    "Taurus",
    "RVR",
    "850",
    "Montero",
    "Aristo",
    "480",
    "Cynos",
    "Autozam AZ-3",
    "Vanette Serena",
    "Prince",
    "Today",
    "Space Runner",
    "Galloper",
    "Espace",
    "Croma",
    "Fargo",
    "Cronos",
    "Sentia",
    "MX-3",
    "Sera",
    "Figaro",
    "Serena",
    "Proceed Marvie",
    "Windom",
    "Corvette",
    "Damas",
    "SC400",
    "MU",
    "Seville",
    "Gloria Cima",
    "Efini MS-9",
    "Pa Nero",
    "180SX",
    "Panda",
    "Tico",
    "S4",
    "Estima Emina",
    "Sprinter Marino",
    "Caldina",
    "Corolla Ceres",
    "Ascot Innova",
    "31029 Волга",
    "Leopard",
    "Carina E",
    "Xedos 6",
    "Frontera",
    "Vento",
    "Sephia",
    "Domani",
    "Emeraude",
    "Libero",
    "Estima Lucida",
    "Caravelle",
    "Largo",
    "Minica",
    "Crown Majesta",
    "Grand Cherokee",
    "Safrane",
    "Scepter",
    "Grandeur",
    "Caprice",
    "S Coupe",
    "CL-Class",
    "M5",
    "Monterey",
    "Eunos 500",
    "Micra",
    "CR-X del Sol",
    "Efini MS-8",
    "Intrepid",
    "Inspire",
    "Colt",
    "Rodeo",
    "Strada",
    "Vision",
    "Impreza",
    "Xantia",
    "Efini MS-6",
    "Impreza WRX",
    "Lancer Evolution",
    "4x4 2131 Нива",
    "4x4 2121 Нива",
    "Rafaga",
    "Musso",
    "Sportage",
    "C-Class",
    "J30",
    "Xedos 9",
    "Terrano II",
    "Twingo",
    "Mondeo",
    "GS300",
    "Jimny Sierra",
    "Viper",
    "Eunos Presso",
    "F150",
    "306",
    "Cavalier",
    "Maverick",
    "Concorde",
    "Lantis",
    "Every",
    "Odyssey",
    "Astro",
    "RAV4",
    "2335",
    "A4",
    "Rasheen",
    "Accent",
    "Range Rover",
    "Tourneo",
    "Felicia",
    "A8",
    "Laguna",
    "A6",
    "Neon",
    "Mistral",
    "Nexia",
    "President",
    "Suburban",
    "Pajero Mini",
    "L400",
    "FTO",
    "Polo",
    "ES300",
    "Tigra",
    "Impreza WRX STI",
    "SVX",
    "Curren",
    "Spectron",
    "Lucino",
    "Aska",
    "Protege",
    "Avalon",
    "MPV",
    "Pajero Junior",
    "CR-V",
    "Proceed Levante",
    "Almera",
    "Espero",
    "Avenir Salut",
    "Bongo Friendee",
    "2110",
    "Baleno",
    "Freda",
    "Saber",
    "406",
    "Stratus",
    "Нива Пикап",
    "Pregio",
    "X-90",
    "Blazer",
    "Carisma",
    "Tahoe",
    "Caddy",
    "Megane",
    "Prairie Joy",
    "Efini MPV",
    "4x4 Бронто",
    "Granvia",
    "DeVille",
    "Cirrus",
    "Avante",
    "Camaro",
    "LX450",
    "S40",
    "Tracker",
    "Swift",
    "Avella",
    "Jumpy",
    "Galaxy",
    "Sharan",
    "Grand Voyager",
    "Millenia",
    "V40",
    "Shuttle",
    "Expert",
    "Primera Camino",
    "Orthia",
    "Partner",
    "Picnic",
    "Berlingo",
    "Lite Ace Noah",
    "Town Ace Noah",
    "Ipsum",
    "Demio",
    "Pyzar",
    "Corona Premio",
    "Wingroad",
    "Camry Gracia",
    "Challenger",
    "Eunos 800",
    "Vito",
    "Terrano Regulus",
    "QX4",
    "Clarus",
    "Scenic",
    "3153",
    "S90",
    "Stagea",
    "Logo",
    "Octavia",
    "Montero Sport",
    "SLK-Class",
    "Ka",
    "A3",
    "Legnum",
    "S8",
    "Expedition",
    "Integra SJ",
    "S70",
    "Coupe",
    "Q45",
    "C70",
    "Outback",
    "V90",
    "Sebring",
    "S-MX",
    "Stepwgn",
    "Tiburon",
    "Cima",
    "Z3",
    "V70",
    "Avenger",
    "Laser",
    "V-Class",
    "Wagon R",
    "3110 Волга",
    "2111",
    "Forester",
    "Corolla Spacio",
    "R'nessa",
    "Avensis",
    "Nubira",
    "Grand Vitara",
    "Mark II Wagon Qualis",
    "Harrier",
    "Torneo",
    "Raum",
    "Lanos",
    "M-Class",
    "Caravan Elgrand",
    "2717",
    "Sienna",
    "CLK-Class",
    "Starex",
    "Atos",
    "Shuma",
    "Hiace Regius",
    "Elgrand",
    "RX-7",
    "Pajero Sport",
    "Terios",
    "A-Class",
    "Prius",
    "2115 Самара",
    "Leganza",
    "VehiCross",
    "XJ",
    "Eldorado",
    "Puma",
    "Kangoo",
    "Wagon R Wide",
    "Chariot Grandis",
    "Space Gear",
    "Xsara",
    "Vita",
    "Homy Elgrand",
    "H1",
    "Tacoma",
    "Chairman",
    "Mira",
    "GS400",
    "Симбир",
    "Gaia",
    "Altezza",
    "RX300",
    "Cube",
    "Familia S-Wagon",
    "Vista Ardeo",
    "Duet",
    "Focus",
    "Tino",
    "LX470",
    "HR-V",
    "Capa",
    "Nadia",
    "Liberty",
    "S80",
    "Mirage Dingo",
    "Legacy Lancaster",
    "Jimny Wide",
    "Bora",
    "206",
    "Storia",
    "Progres",
    "Pajero iO",
    "Z",
    "Freelander",
    "Legacy B4",
    "Carnival",
    "Wizard",
    "Terios Kid",
    "Presage",
    "300M",
    "Clio",
    "Life",
    "Toppo BJ",
    "Land Cruiser Cygnus",
    "Pleo",
    "Alero",
    "Sentra",
    "2120 Надежда",
    "Space Star",
    "Beetle",
    "Aspire",
    "Cougar",
    "Matiz",
    "Solara",
    "XG",
    "Bravo",
    "LHS",
    "911",
    "Lupo",
    "Premacy",
    "2112",
    "Vitz",
    "Funcargo",
    "Platz",
    "Echo",
    "X5",
    "Pajero Pinin",
    "Yaris",
    "Grand Hiace",
    "IS200",
    "Magnus",
    "Xsara Picasso",
    "Yaris Verso",
    "Avancier",
    "Cami",
    "Kei",
    "Touring Hiace",
    "607",
    "Trajet",
    "Zafira",
    "Wagon R Plus",
    "Civic Type R",
    "F250",
    "Cuore",
    "3159",
    "S-type",
    "Tundra",
    "Toppo BJ Wide",
    "Symbol",
    "TT",
    "I30",
    "Equus",
    "Town Box Wide",
    "Bassara",
    "Regius",
    "AZ-Offroad",
    "Crew",
    "Mega Cruiser",
    "S6",
    "Charade Social",
    "Saxo",
    "March Box",
    "Xterra",
    "Excursion",
    "Alto",
    "Ixion",
    "Dakota",
    "3111 Волга",
    "Stream",
    "Corolla Fielder",
    "Bluebird Sylphy",
    "X-Trail",
    "Santa Fe",
    "Opa",
    "Rio",
    "Escape",
    "Wagon R Solio",
    "Kluger V",
    "Dion",
    "Lancer Cedia",
    "Pronard",
    "Grand Escudo",
    "S60",
    "LS430",
    "Magentis",
    "YRV",
    "PT Cruiser",
    "Славута",
    "WiLL Vi",
    "Corolla Altis",
    "XC70",
    "bB",
    "Atrai7",
    "Fabia",
    "Sequoia",
    "Grand Vitara XL-7",
    "Tribute",
    "A6 allroad quattro",
    "Grand Caravan",
    "Boxster",
    "MR-S",
    "Sparky",
    "Ignis",
    "Scenic RX4",
    "GS430",
    "Move",
    "MW",
    "Tacuma",
    "Spectra",
    "Frontier",
    "Aerio",
    "Highlander",
    "Matrix",
    "Fit",
    "Verossa",
    "Airtrek",
    "Allion",
    "SC430",
    "Hatch",
    "Premio",
    "Noah",
    "WiLL VS",
    "Allex",
    "Terracan",
    "307",
    "Corolla Runx",
    "Rexton",
    "Safe",
    "Avensis Verso",
    "Voxy",
    "MR Wagon",
    "Liana",
    "Brevis",
    "Avalanche",
    "eK Wagon",
    "Traviq",
    "C5",
    "TrailBlazer",
    "Corolla Verso",
    "Superb",
    "Mobilio",
    "Doblo",
    "Cruze",
    "M3",
    "X-Type",
    "Max",
    "Escalade",
    "Altima",
    "Trafic",
    "Axiom",
    "Vel Satis",
    "Sambar",
    "Ram",
    "Mark II Wagon Blit",
    "Voltz",
    "Niva",
    "Succeed",
    "Sorento",
    "GX470",
    "Touareg",
    "Outlander",
    "Alphard",
    "Probox",
    "Murano",
    "Tourneo Connect",
    "Getz",
    "WiLL Cypha",
    "ist",
    "C3",
    "FX35",
    "Moco",
    "Atenza",
    "Sens",
    "Mazda6",
    "Musso Sports",
    "Fit Aria",
    "XC90",
    "Lacetti",
    "Alto Lapin",
    "Carens",
    "Vios",
    "G35",
    "Aveo",
    "Fusion",
    "eK Sport",
    "807",
    "Mazda2",
    "That's",
    "21261 Фабула",
    "Mobilio Spike",
    "B-Series",
    "Hijet",
    "Vaneo",
    "Phaeton",
    "CTS",
    "Pilot",
    "Jazz",
    "Kalos",
    "Copen",
    "350Z",
    "Mira Avy",
    "2114 Самара",
    "Amulet A15",
    "Wish",
    "31105 Волга",
    "RX330",
    "Combo",
    "Grandis",
    "Element",
    "Хантер",
    "Mazda3",
    "FX45",
    "X3",
    "Cayenne",
    "6-Series",
    "Touran",
    "Pacifica",
    "Teana",
    "C-MAX",
    "SRX",
    "Durango",
    "Meriva",
    "Punto",
    "MDX",
    "RX-8",
    "Armada",
    "C2",
    "Picanto",
    "Axela",
    "Signum",
    "Opirus",
    "Sienta",
    "Titan",
    "R2",
    "Viano",
    "Cube Cubic",
    "Regius Ace",
    "Optima",
    "Quest",
    "IS300",
    "Crossfire",
    "Endeavor",
    "Spiano",
    "V50",
    "Z4",
    "Tucson",
    "Калина",
    "Cerato",
    "407",
    "C4",
    "Mark X",
    "B9 Tribeca",
    "300C",
    "1-Series",
    "Passo",
    "Tiida Latio",
    "2113 Самара",
    "Elysion",
    "QX56",
    "Fuga",
    "CLS-Class",
    "Pointer",
    "Edix",
    "Viva",
    "Boon",
    "Porte",
    "Isis",
    "Tiida",
    "Colt Plus",
    "Golf Plus",
    "Mazda5",
    "STS",
    "Evanda",
    "Verisa",
    "Lafesta",
    "R1",
    "ES330",
    "Cayman",
    "XK",
    "Town Box",
    "Astra GTC",
    "Magnum",
    "RX400h",
    "Tiggo T11",
    "Ridgeline",
    "AZ-Wagon",
    "IS250",
    "Belta",
    "Airwave",
    "Logan",
    "Патриот",
    "Ractis",
    "NF",
    "C1",
    "QQ Sweet",
    "Actyon",
    "Range Rover Sport",
    "R-Class",
    "Mazda6 MPS",
    "IS220d",
    "Charger",
    "Spark",
    "Note",
    "B-Class",
    "M6",
    "Hover",
    "Fortuner",
    "IS350",
    "Focus ST",
    "GS350",
    "FR-V",
    "Gentra",
    "2330 Тигр",
    "M45",
    "Aygo",
    "Solio",
    "Grand Scenic",
    "1007",
    "Otti",
    "Kyron",
    "DTS",
    "HHR",
    "Grande Punto",
    "Oriental Son B11",
    "207",
    "Mazda3 MPS",
    "BLS",
    "RX350",
    "Rezzo",
    "Corolla Axio",
    "Almera Classic",
    "SX4",
    "Epica",
    "Navara",
    "Ceed",
    "Q7",
    "CX-7",
    "GL-Class",
    "S-MAX",
    "Captiva",
    "Qashqai",
    "M35",
    "ES350",
    "Cervo",
    "Auris",
    "Actyon Sports",
    "Nitro",
    "Zest",
    "Roomster",
    "Caliber",
    "Winstorm",
    "Carol",
    "i",
    "Blade",
    "Antara",
    "LS460",
    "GS450h",
    "LS460L",
    "Compass",
    "Eos",
    "Ranger",
    "FJ Cruiser",
    "Rush",
    "ProCeed",
    "Commander",
    "R8",
    "C30",
    "BT-50",
    "XL7",
    "Be-Go",
    "Sonica",
    "S1",
    "Esse",
    "Veracruz",
    "Wingle",
    "Coo",
    "Stella",
    "Patriot",
    "Vivaro",
    "Fora A21",
    "Приора",
    "308",
    "Santa Fe Classic",
    "i30",
    "C4 Picasso",
    "Сенс",
    "A5",
    "S5",
    "LX570",
    "Linea",
    "LS600hL",
    "Corolla Rumion",
    "Breez",
    "107",
    "Dualis",
    "Vanguard",
    "Journey",
    "Grand C4 Picasso",
    "Otaka CK",
    "Pino",
    "LS600h",
    "Crossroad",
    "Rodius",
    "Mark X Zio",
    "Delica D:5",
    "Edge",
    "Town and Country",
    "Rogue",
    "Landy",
    "i10",
    "Vamos",
    "MX-5",
    "Tanto",
    "RS6",
    "FX37",
    "Passat CC",
    "Q5",
    "Tiguan",
    "XC60",
    "Freed",
    "G37",
    "Kimo A1",
    "Soul",
    "GLK-Class",
    "CX-9",
    "Калина Спорт",
    "Dex",
    "S3",
    "Clubman",
    "Пикап",
    "Шанс",
    "Estina",
    "4007",
    "Vellfire",
    "Kix",
    "NP300",
    "Koleos",
    "500",
    "QQ6 S21",
    "EX35",
    "Biante",
    "iQ",
    "Kuga",
    "C-Crosser",
    "Insignia",
    "Forte",
    "Qashqai+2",
    "Волга Сайбер",
    "FX50",
    "Partner Tepee",
    "XF",
    "TTS",
    "Scirocco",
    "CrossEastar B14",
    "Passo Sette",
    "Roadster",
    "Splash",
    "Clipper",
    "Toppo",
    "Boon Luminas",
    "Venza",
    "CLC-Class",
    "Exiga",
    "GT-R",
    "Genesis",
    "Move Conte",
    "Tribeca",
    "Modus",
    "Partner Origin",
    "X6",
    "Nemo",
    "Insight",
    "RX450h",
    "Sandero",
    "Yeti",
    "i20",
    "5-Series Gran Turismo",
    "GX460",
    "NV200",
    "ix35",
    "Panamera",
    "X1",
    "A4 allroad quattro",
    "C3 Picasso",
    "ix55",
    "Verso",
    "Sai",
    "HS250h",
    "Transporter",
    "Roox",
    "DS3",
    "Palette",
    "Tanto Exe",
    "Equinox",
    "Cabrio",
    "Skyline Crossover",
    "Crosstour",
    "Dias Wagon",
    "Fluence",
    "5008",
    "IS350C",
    "Pixo",
    "Duster",
    "A7",
    "Sandero Stepway",
    "Solaris",
    "CR-Z",
    "Solano",
    "Smily",
    "ASX",
    "Juke",
    "G25",
    "Tingo",
    "CT200h",
    "Countryman",
    "Freed Spike",
    "RX270",
    "3008",
    "Cerato Koup",
    "Impreza XV",
    "Hover H3",
    "Kizashi",
    "RCZ",
    "K5",
    "Corda",
    "Latitude",
    "M37",
    "M11",
    "Volt",
    "RS5",
    "M25",
    "Trezia",
    "Amarok",
    "FX30d",
    "A1",
    "M56",
    "Lucra",
    "IS250C",
    "EX37",
    "Scrum",
    "Grand C-MAX",
    "Galant Fortis",
    "Prius Alpha",
    "Гранта",
    "Venga",
    "MK Cross",
    "Fit Shuttle",
    "Hover H5",
    "Very A13",
    "CX-5",
    "Aqua",
    "indiS S18D",
    "Range Rover Evoque",
    "Bonus A13",
    "Orlando",
    "EX25",
    "RS3",
    "Astra Family",
    "Q3",
    "Pride",
    "Mohave",
    "N-BOX",
    "Delica D:2",
    "MK",
    "Veloster",
    "XV",
    "V60",
    "Delica D:3",
    "Mira e:S",
    "Pixis Space",
    "Cobalt",
    "Ларгус",
    "Emgrand EC7",
    "Mokka",
    "Sylphy",
    "Latio",
    "Spade",
    "Vamos Hobio",
    "X60",
    "ES250",
    "GT 86",
    "Korando Sports",
    "Pixis Epoch",
    "Prius PHV",
    "GS250",
    "Besturn B50",
    "Ypsilon",
    "408",
    "Вида",
    "Rapid",
    "DS4",
    "DS5",
    "C4 Aircross",
    "N-ONE",
    "i40",
    "508",
    "Quoris",
    "Malibu",
    "ES300h",
    "4008",
    "ATS",
    "Acty",
    "JX35",
    "V5",
    "BRZ",
    "Paceman",
    "Prius C",
    "up!",
    "370Z",
    "V2",
    "Flair",
    "Dart",
    "QX70",
    "N-WGN",
    "Spacia",
    "N-BOX+",
    "Vezel",
    "CLA-Class",
    "Гранта Спорт",
    "RS Q3",
    "Silverado",
    "GLA-Class",
    "DAYZ",
    "4-Series",
    "QX50",
    "ek Custom",
    "QX80",
    "208",
    "301",
    "Hover M2",
    "3-Series Gran Turismo",
    "C-Elysee",
    "Nomad",
    "QX60",
    "Macan",
    "Emgrand X7",
    "IS300h",
    "Q50",
    "GS300h",
    "RS7",
    "NV100 Clipper",
    "Citan",
    "SQ5",
    "F-Type",
    "Hover M4",
    "Korando Turismo",
    "ELR",
    "Impala",
    "Mebius",
    "Hover H6",
    "Flair Wagon",
    "NX200t",
    "Levorg",
    "Esquire",
    "EcoSport",
    "on-DO",
    "NX300h",
    "4x4 Урбан",
    "AMG GT",
    "Hustler",
    "M4",
    "Tiggo 5",
    "i3",
    "Cebrium",
    "NX200",
    "X4",
    "2008",
    "Oley",
    "Scudo",
    "Калина Кросс",
    "eK Space",
    "CS35",
    "DAYZ Roox",
    "i8",
    "Grand Santa Fe",
    "Flair Crossover",
    "Bonus 3 - A19",
    "2-Series Active Tourer",
    "Discovery Sport",
    "Wake",
    "H30 Cross",
    "Q70",
    "Prius v",
    "Arrizo 7",
    "N-BOX Slash",
    "Trax",
    "H6",
    "Pleo Plus",
    "C4 Cactus",
    "RC350",
    "Celliya",
    "2-Series",
    "Ларгус Кросс",
    "Tourneo Courier",
    "Веста",
    "Jade",
    "CX-3",
    "RX200t",
    "GLE",
    "mi-Do",
    "S660",
    "X50",
    "GLC",
    "GLE Coupe",
    "RC300h",
    "RC200t",
    "LX450d",
    "2-Series Gran Tourer",
    "IS200t",
    "Q30",
    "XE",
    "ES200",
    "Talisman",
    "Renegade",
    "H9",
    "H2",
    "Cast",
    "GS200t",
    "GLS-Class",
    "Freed+",
    "C-HR",
    "Tank",
    "Kodiaq",
    "Kaptur",
    "Thor",
    "Creta",
    "K7",
    "Roomy",
    "Colorado",
    "GLC Coupe",
    "Х-рей",
    "D-MAX",
    "Minicab",
    "Fullback",
    "Pixis Joy",
    "K3",
    "QX30",
    "Prius Prime",
    "Q2",
    "Yaris iA",
    "XT5",
    "SQ7",
    "SLC-Class",
    "Kadjar",
    "M2",
    "Pixis Mega",
    "Niro",
    "Kona",
    "Stonic",
    "CX-8",
    "Myway",
    "Tiggo 2",
    "NX300",
    "RX450hL",
    "Веста Кросс",
    "LC500h",
    "Xbee",
    "G80",
    "Range Rover Velar",
    "X2",
    "Tiggo 3",
    "Murman",
    "Arteon",
    "Rio X (X-Line)",
    "6-Series Gran Turismo",
    "LC500",
    "Xpander",
    "LS500",
    "Tiguan Allspace",
    "Eclipse Cross",
    "AX7",
    "CT6",
    "E-Pace",
    "Chiffon",
    "Dokker",
    "Traveller",
    "Altis",
    "Traverse",
    "RX350L",
    "Tivoli",
    "NV350 Caravan",
    "LS500h",
    "Spacetourer",
    "RC300",
    "Karoq",
    "Palisade",
    "N-VAN",
    "G70",
    "Х-рей Кросс",
    "Stinger",
    "UX200",
    "Logan Stepway",
    "C3 Aircross",
    "Ascent",
    "XC40",
    "Teramont",
    "UX250h",
    "X-Class",
    "Ertiga",
    "Atlas",
    "Q8",
    "Grandland X",
    "California",
    "X70",
    "Move Canbus",
    "Веста Спорт",
    "Mira Tocot",
    "Ciaz",
    "GLB-Class",
    "Гранта Кросс",
    "X7",
    "Arkana",
    "F7",
    "Tiggo 4",
    "F7x",
    "Raize",
    "Tiggo 7",
    "Gladiator",
    "Zafira Life",
    "K900",
    "CX-30",
    "Cayenne Coupe",
    "CS75 Plus",
    "CS55",
    "Besturn X40",
    "Seltos",
    "CS35 Plus",
    "T6",
    "CX-4",
    "G90",
    "Venue",
    "M8",
    "Crossover",
    "Q3 Sportback",
    "Dokker Stepway",
    "GranAce",
    "T-Cross",
    "C5 Aircross",
    "SQ8",
    "Scala",
    "580",
    "Kicks",
    "Tugella FY11",
    "Tiggo 7 Pro",
    "GV80",
    "TXL",
    "Нива (2020-21 гг.)",
    "J7",
    "Tiggo 8",
    "Coolray SX11",
    "Wingle 7",
    "Yaris Cross",
    "UNI-T",
    "H5",
    "Xceed",
    "Tiguan X",
    "XT6",
    "XT4",
    "Pao",
    "Taft",
    "Corolla Cross",
    "MX-30",
    "Q60",
    "Tiggo 8 Pro",
    "Нива Легенд",
    "VX",
    "Нива Тревел",
    "Jolion",
    "Atlas Pro",
    "Taos",
    "Staria",
    "UNI-K",
    "GR 86",
    "NX250",
    "GV70",
    "LX600",
    "Нива Бронто",
    "NX350h",
    "Crosstrek",
    "QX55",
    "Grand Wagoneer",
    "NX350",
    "Poer",
    "LX500d",
    "F-Pace",
    "SQ5 Sportback",
    "Q5 Sportback",
    "Tiggo 8 Pro Max",
    "Tiggo 4 Pro",
    "Torres",
    "Tiggo 7 Pro Max",
    "CS55 Plus",
    "LX",
    "UNI-V",
    "JS6",
    "K9",
    "Dargo",
    "3",
    "DF6",
    "CS85 Coupe",
    "JS4",
    "RX500h",
    "Teramont X",
    "RX350h",
    "CX-60",
    "Monjaro",
    "Bestune T55",
    "E5"
]